Repository Kernel360/f1-JDON-Backend, pull requests merged in 2023-12, with the labels that each got.

#9 Feature: Faq 상세조회
  module-api/src/main/java/kernel/jdon/ModuleApiApplication.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/controller/FaqController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/dto/FindFaqResponse.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/entity/Faq.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/repository/FaqRepository.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/service/FaqService.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/common/entity/.gitkeep
  module-api/src/main/java/kernel/jdon/moduleapi/global/common/entity/BaseEntity.java
  module-api/src/main/resources/application.yml
  module-api/src/test/java/kernel/jdon/moduleapi/.gitkeep
  module-api/src/test/java/kernel/jdon/moduleapi/domain/faq/service/FaqServiceTest.java
Labels: :sparkles: Feature

#11 [Chore] 테스트환경 구축
  module-api/build.gradle
  module-api/src/test/java/kernel/jdon/moduleapi/domain/faq/service/FaqServiceTest.java
  module-api/src/test/resources/application.yml
Labels: ⚙️ Settings, 🔨 Refactor, :test_tube: Test

#12 Feature: FAQ 삭제기능 개발 및 테스트
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/controller/FaqController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/service/FaqService.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/faq/service/FaqServiceTest.java
Labels: :sparkles: Feature, :test_tube: Test

#13 Feature: Faq 수정 api 구현
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/controller/FaqController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/dto/request/ModifyFaqRequest.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/dto/response/ModifyFaqResponse.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/entity/Faq.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/service/FaqService.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/faq/service/FaqServiceTest.java
Labels: :sparkles: Feature, :test_tube: Test

#14 Feature: FAQ 등록
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/controller/FaqController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/dto/request/CreateFaqRequest.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/dto/response/CreateFaqResponse.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/dto/response/FindFaqResponse.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/service/FaqService.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/faq/service/FaqServiceTest.java
Labels: :sparkles: Feature, :test_tube: Test

#15 Chore: Update PR template
  .github/pull_request_template.md
Labels: 📑 Docs

#18 Docs: Update issue templates
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: 📑 Docs

#20 Refactor: delete @Builder from CreateFaqRequest and use reflection me…
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/dto/request/CreateFaqRequest.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/faq/service/FaqServiceTest.java
Labels: 🔨 Refactor

#29 Feature: FAQ 목록조회 API 구현
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/controller/FaqController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/dto/response/FindListFaqResponse.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/service/FaqService.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/faq/service/FaqServiceTest.java
Labels: :sparkles: Feature, :test_tube: Test

#32 Feature: ErrorCode, FaqErrorCode 생성 및 적용
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/service/FaqService.java
  module-common/build.gradle
  module-common/src/main/java/kernel/jdon/modulecommon/error/code/ErrorCode.java
  module-common/src/main/java/kernel/jdon/modulecommon/error/code/FaqErrorCode.java
  module-common/src/main/java/kernel/jdon/modulecommon/error/exception/api/ApiException.java
Labels: :sparkles: Feature, ⚙️ Settings, 🔨 Refactor

#35 Chore: module-domain 모듈 생성
  module-domain/build.gradle
  module-domain/gradle/wrapper/gradle-wrapper.jar
  module-domain/gradle/wrapper/gradle-wrapper.properties
  module-domain/gradlew
  module-domain/gradlew.bat
  module-domain/settings.gradle
  settings.gradle
Labels: ⚙️ Settings

#40 Fix: Add faqId at FindFaqListResponse
  module-api/src/test/java/kernel/jdon/moduleapi/domain/faq/service/FaqServiceTest.java
  module-domain/src/main/java/kernel/jdon/faq/dto/response/FindFaqResponse.java
Labels: 🐞 Bug, 🐞🔨 Bugfix, :test_tube: Test

#42 Chore: jdk 버전 변경(21 -> 17) 및 하위 모듈 settings.gradle 파일 삭제
  build.gradle
  module-api/build.gradle
  module-api/settings.gradle
  module-common/build.gradle
  module-common/settings.gradle
  module-domain/build.gradle
  module-domain/settings.gradle
Labels: ⚙️ Settings

#44 Feature: ExceptionHandler 구현
  module-common/src/main/java/kernel/jdon/dto/response/ErrorResponse.java
  module-common/src/main/java/kernel/jdon/error/exception/GlobalExceptionHandler.java
  module-common/src/main/java/kernel/jdon/error/exception/api/ApiException.java
Labels: :sparkles: Feature

#48 Chore: module-api 빌드설정 수정(plain.jar 생성X)
  module-api/build.gradle
Labels: ⚙️ Settings

#50 Feature: api모듈 logback 적용 및 common, domain 모듈 prepareKotlinBuildScriptModel 적용
  module-api/src/main/resources/application.yml
  module-api/src/main/resources/logback-spring.xml
  module-common/build.gradle
  module-domain/build.gradle
Labels: 🐞 Bug, :sparkles: Feature

#54 Bug: 엔티티 columnDefinition BIGINT 변경
  module-domain/src/main/java/kernel/jdon/coffeechat/domain/CoffeeChat.java
  module-domain/src/main/java/kernel/jdon/coffeechatmember/domain/CoffeeChatMember.java
  module-domain/src/main/java/kernel/jdon/favorite/domain/Favorite.java
  module-domain/src/main/java/kernel/jdon/inflearn/domain/Inflearn.java
  module-domain/src/main/java/kernel/jdon/jobcategory/domain/JobCategory.java
  module-domain/src/main/java/kernel/jdon/member/domain/Member.java
  module-domain/src/main/java/kernel/jdon/memberskill/domain/MemberSkill.java
  module-domain/src/main/java/kernel/jdon/skill/domain/Skill.java
  module-domain/src/main/java/kernel/jdon/wanted/domain/WantedJd.java
  module-domain/src/main/java/kernel/jdon/wantedskill/domain/WantedJdSkill.java
Labels: 🐞 Bug

#56 Fix: 폼 로그인 설계 변경으로 인한 Member 엔티티 수정
  module-domain/src/main/java/kernel/jdon/member/domain/Member.java
Labels: 🐞🔨 Bugfix

#58 Chore: 모듈 별 config 파일 이동
  module-domain/src/main/java/kernel/jdon/config/JpaAuditingConfig.java
Labels: 🐞 Bug
