Repository Kernel360/f1-JDON-Backend, pull requests merged in 2024-04, with the labels that each got.

#557 Fix: 엔티티 @ManyToOne 필드 notnull 속성 추가
  module-domain/src/main/java/kernel/jdon/moduledomain/faq/domain/Faq.java
  module-domain/src/main/java/kernel/jdon/moduledomain/favorite/domain/Favorite.java
  module-domain/src/main/java/kernel/jdon/moduledomain/inflearnjdskill/domain/InflearnJdSkill.java
  module-domain/src/main/java/kernel/jdon/moduledomain/member/domain/Member.java
  module-domain/src/main/java/kernel/jdon/moduledomain/memberskill/domain/MemberSkill.java
  module-domain/src/main/java/kernel/jdon/moduledomain/skill/domain/Skill.java
  module-domain/src/main/java/kernel/jdon/moduledomain/skillhistory/domain/SkillHistory.java
  module-domain/src/main/java/kernel/jdon/moduledomain/skillkeyword/domain/SkillKeyword.java
Labels: ✏️ Fix

#561 Docs: gif 및 설명 수정
  README.md
Labels: 📑 Docs, 👷 NO-Deploy

#559 fix: 커피챗 동시성 제어를 위한 락 획득과 반납 과정을 더 명확히 알기 위해 로그 추가
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/application/CoffeeChatFacade.java
Labels: ✏️ Fix

#565 Fix: 수동 트리거를 사용하여 deploy 하도록 수정
  .github/workflows/dev-cicd.yml
  .github/workflows/prev-ci.yml
  .github/workflows/prod-cicd.yml
Labels: 🌏 Deploy

#567 Feat: Job 로깅 AOP PointCut 추가
  module-common/src/main/java/kernel/jdon/modulecommon/log/aspect/QueryCounterAspect.java
Labels: :sparkles: Feature, 🌏 Batch-Deploy

#564 BugFix: NotNull 조건 추가로 통합테스트 에러 해결
  module-api/src/test/java/kernel/jdon/moduleapi/domain/favorite/presentation/FavoriteControllerIntegrationTest.java
  module-domain/src/main/java/kernel/jdon/moduledomain/jobcategory/domain/JobCategory.java
Labels: 🐞🔨 Bugfix

#562 Docs: readme 문구 수정 및 ERD 업데이트
  README.md
  docs/images/jdon_erd.png
Labels: 📑 Docs

#569 BugFix: QueryCounter 어노테이션 생성 및 AOP 포인트컷 적용
  module-batch/src/main/java/kernel/jdon/modulebatch/scheduler/JdScheduler.java
  module-common/src/main/java/kernel/jdon/modulecommon/log/annotation/QueryCounter.java
  module-common/src/main/java/kernel/jdon/modulecommon/log/aspect/QueryCounterAspect.java
Labels: 🐞🔨 Bugfix

#573 Chore: 원티드 스크래핑 배치 코드 오타 수정 및 부분 리팩토링
  module-batch/src/main/java/kernel/jdon/modulebatch/domain/wantedjdskill/repository/WantedJdSkillDao.java
  module-batch/src/main/java/kernel/jdon/modulebatch/global/config/ScrapingWantedProperties.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/reader/PartBackendWantedJdItemReader.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/reader/PartFrontendWantedJdItemReader.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/reader/fetchmanager/JobDetailFetchManager.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/reader/fetchmanager/JobListFetchManager.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/writer/WantedJdItemWriter.java
  module-batch/src/main/resources/constant/scraping.yml
Labels: 🔨 Refactor, :green_heart: Chore

#568 Docs: Readme 개발기록 문구 제거 및 사진 변경
  README.md
  docs/images/jdon-architecture.png
  docs/images/jdon-erd.png
  docs/images/jdon-server.png
  docs/images/jdon_architecture.png
Labels: 📑 Docs

#578 Refactor: 커버링 인덱스를 활용하도록 쿼리 분리
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatRepositoryImpl.java
Labels: 🔨 Refactor

#580 Refactor: 커피챗 목록조회 API 동적쿼리에서 join을 서브쿼리로 대체
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatRepositoryImpl.java
Labels: 🔨 Refactor

#582 Fix: 커넥션풀 사이즈 20으로 조정
  module-api/src/main/resources/application-dev.yml
Labels: ✏️ Fix

#584 Fix: 커넥션풀 사이즈 30으로 조정
  module-api/src/main/resources/application-dev.yml
Labels: ✏️ Fix

#585 Fix: 원티드 채용공고 스크래핑 API 따닥 제어
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/application/CoffeeChatFacade.java
  module-crawler/build.gradle
  module-crawler/src/main/java/kernel/jdon/modulecrawler/domain/jd/application/JdFacade.java
  module-crawler/src/main/java/kernel/jdon/modulecrawler/domain/jd/core/JdServiceImpl.java
  module-crawler/src/main/java/kernel/jdon/modulecrawler/domain/jd/error/JdErrorCode.java
  module-crawler/src/main/resources/application.yml
  module-crawler/src/test/java/kernel/jdon/modulecrawler/domain/jd/application/JdFacadeTest.java
  module-crawler/src/test/resources/application.yml
Labels: :test_tube: Test, ✏️ Fix

#586 Deploy: 4월 2주차 수시배포
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/application/CoffeeChatFacade.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatRepositoryImpl.java
  module-api/src/main/resources/application-dev.yml
  module-crawler/build.gradle
  module-crawler/src/main/java/kernel/jdon/modulecrawler/domain/jd/application/JdFacade.java
  module-crawler/src/main/java/kernel/jdon/modulecrawler/domain/jd/core/JdServiceImpl.java
  module-crawler/src/main/java/kernel/jdon/modulecrawler/domain/jd/error/JdErrorCode.java
  module-crawler/src/main/resources/application.yml
  module-crawler/src/test/java/kernel/jdon/modulecrawler/domain/jd/application/JdFacadeTest.java
  module-crawler/src/test/resources/application.yml
Labels: 🌏 Deploy

#588 BugFix: profile별 application.yml 분리 및 redis 설정
  module-api/src/main/resources/application-local.yml
  module-crawler/src/main/resources/application-dev.yml
  module-crawler/src/main/resources/application-local.yml
  module-crawler/src/main/resources/application-prod.yml
  module-crawler/src/main/resources/application.yml
Labels: 🐞🔨 Bugfix

#590 Fix: 스레드풀 사이즈 20으로 조정
  module-api/src/main/resources/application-dev.yml
Labels: ✏️ Fix

#600 Feature: crawler 모듈 실행 시 슬랙알림 설정
  module-crawler/src/main/java/kernel/jdon/ModuleCrawlerApplication.java
  module-crawler/src/main/resources/application-dev.yml
  module-crawler/src/main/resources/application-prod.yml
Labels: :sparkles: Feature

#602 Fix: 톰캣 스레드풀 메트릭 노출 설정
  module-api/src/main/resources/application-dev.yml
Labels: ✏️ Fix

#604 Refactor: 원티드 스크래핑 객체 리팩토링
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/reader/AllBackendWantedJdItemReader.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/reader/AllFrontendWantedJdItemReader.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/reader/PartBackendWantedJdItemReader.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/reader/PartFrontendWantedJdItemReader.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/reader/WantedJdClient.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/reader/dto/WantedJobDetailResponse.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/reader/dto/WantedJobListResponse.java
  module-crawler/src/main/java/kernel/jdon/modulecrawler/domain/jd/core/JdServiceImpl.java
  module-crawler/src/main/java/kernel/jdon/modulecrawler/domain/jd/core/dto/WantedJobListResponse.java
Labels: 🔨 Refactor

#606 Fix: deploy시, 운영서버의 code를 받는 branch명 수정
  .github/workflows/dev-cicd.yml
  .github/workflows/prod-cicd.yml
Labels: ✏️ Fix
