Repository Kernel360/f1-JDON-Backend, pull requests merged in 2024-03, with the labels that each got.

#382 Fix: 리뷰목록조회 시간 역순 정렬조건 추가
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/infrastructure/ReviewRepositoryImpl.java
Labels: 🐞🔨 Bugfix

#388 Fix: 로그인 redirect url, 세션 유지 시간, 닉네임 불가 단어 검증에 대한 수정
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/presentation/MemberDto.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/annotation/validate/IsValidNickname.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/JdonAuthExceptionHandler.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/JdonLogoutSuccessHandler.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/JdonOAuth2AuthenticationSuccessHandler.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/LoginRedirectUrlProperties.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/OAuth2SecurityConfig.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/RedirectUrlUtil.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/validate/InvalidNickname.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/validate/NicknameValidator.java
  module-api/src/main/resources/application-dev.yml
  module-api/src/main/resources/application-local.yml
  module-api/src/main/resources/application-prod.yml
  module-api/src/main/resources/application.yml
Labels: 🐞🔨 Bugfix

#380 Chore: 코드컨벤션에 맞춰 메서드명, dto 수정
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/application/CoffeeChatFacade.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatService.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatDto.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatDtoMapper.java
Labels: 🔨 Refactor, :green_heart: Chore

#384 Feature: 커피챗, 리뷰 DTO Validation 반영
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatDto.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/presentation/ReviewDto.java
Labels: :sparkles: Feature

#390 Chore: Faq 도메인 코드를 코드컨벤션에 맞도록 수정
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/application/FaqFacade.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/application/FaqReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/application/FaqStore.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/core/FaqCommand.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/core/FaqInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/core/FaqReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/core/FaqService.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/core/FaqServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/infrastructure/FaqReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/infrastructure/FaqStoreImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/presentation/FaqController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/presentation/FaqDto.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/presentation/FaqDtoMapper.java
  module-api/src/test/java/kernel/jdon/faq/service/FaqServiceTest.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/faq/application/FaqFacadeTest.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/faq/core/FaqServiceImplTest.java
Labels: :test_tube: Test, :green_heart: Chore

#374 Fix: 로그인 상태 조회 API의 json key값 수정
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/presentation/MemberDto.java
Labels: 🐞🔨 Bugfix

#393 BugFix: 인프런 크롤링 에러 발생 해결
  module-crawler/src/main/java/kernel/jdon/modulecrawler/inflearn/service/CourseStorageService.java
  module-crawler/src/main/java/kernel/jdon/modulecrawler/wanted/repository/InflearnCourseRepository.java
Labels: 🐞🔨 Bugfix

#395 Refactor: 공통된 page 변수들을 객체로 바인딩
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/presentation/FavoriteController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/presentation/ReviewController.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/page/PageInfoRequest.java
Labels: 🔨 Refactor

#396 Fix: 연관 검색어 키워드 조회 메서드 명 변경 및 메서드 설명 추가
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillKeywordManager.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillRepositoryImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/presentation/SkillController.java
  module-domain/src/main/java/kernel/jdon/moduledomain/skill/domain/SkillType.java
Labels: ✏️ Fix

#404 Test: Jd 도메인 단위 테스트 작성
  module-api/src/test/java/kernel/jdon/moduleapi/domain/favorite/application/FavoriteFacadeTest.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/favorite/core/FavoriteServiceImplTest.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/jd/application/JdFacadeTest.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/jd/core/JdServiceImplTest.java
Labels: :test_tube: Test

#402 Test: 내 정보 조회 & 수정 API의 TEST code 작성
  module-api/src/main/java/kernel/jdon/moduleapi/global/validate/PastDateValidator.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/member/application/MemberFacadeTest.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/member/core/MemberServiceImplTest.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/member/infrastructure/MemberFactoryImplTest.java
Labels: :test_tube: Test, ✏️ Fix

#408 Test: 회원가입, 닉네임 중복확인 API | TEST code 작성
  module-api/src/test/java/kernel/jdon/moduleapi/domain/member/application/MemberFacadeTest.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/member/core/MemberServiceImplTest.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/member/infrastructure/MemberFactoryImplTest.java
Labels: :test_tube: Test

#407 Refactor: Review 등록 Factory 적용
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewFactory.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/infrastructure/ReviewFactoryImpl.java
Labels: 🔨 Refactor

#411 Test: Review 도메인 단위 테스트 코드 작성
  module-api/src/test/java/kernel/jdon/moduleapi/domain/review/application/ReviewFacadeTest.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/review/core/ReviewServiceImplTest.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/review/infrastructure/ReviewFactoryImplTest.java
  module-api/src/test/resources/giventest/review/serviceimpl/1_review.json
  module-domain/src/main/java/kernel/jdon/moduledomain/review/domain/Review.java
Labels: :test_tube: Test

#410 Test: 회원탈퇴 API | TEST code 작성
  module-api/src/test/java/kernel/jdon/moduleapi/domain/member/application/MemberFacadeTest.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/member/core/MemberServiceImplTest.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/member/infrastructure/MemberFactoryImplTest.java
Labels: :test_tube: Test

#413 Feat: 커피챗 신청 취소 API 구현
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/application/CoffeeChatFacade.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatService.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatStore.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/error/CoffeeChatErrorCode.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatMemberRepository.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatStoreImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatDto.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatDtoMapper.java
  module-domain/src/main/java/kernel/jdon/moduledomain/coffeechat/domain/CoffeeChat.java
Labels: :sparkles: Feature

#422 Chore: 연관어 수정
  module-domain/src/main/java/kernel/jdon/moduledomain/skill/domain/BackendSkillType.java
  module-domain/src/main/java/kernel/jdon/moduledomain/skill/domain/FrontendSkillType.java
Labels: :green_heart: Chore

#425 Refactor: 마이페이지 커피챗 목록조회 API 특정 구현기술 의존성 제거
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/application/CoffeeChatFacade.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatService.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatController.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/page/CustomPageResponse.java
Labels: 🔨 Refactor

#419 Test: 찜하기/취소하기, 찜 조회하기 컨트롤러 통합 테스트 작성
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/core/FavoriteServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/presentation/FavoriteDto.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/favorite/presentation/FavoriteControllerIntegrationTest.java
  module-api/src/test/resources/application.yml
Labels: :test_tube: Test

#424 Refactor: 찜하기 API 추상화 수정
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/core/FavoriteReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/infrastructure/FavoriteFactoryImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/infrastructure/FavoriteReaderImpl.java
Labels: 🔨 Refactor

#426 Fix: 리뷰 목록 조회 무한스크롤 페이징 적용
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/application/ReviewFacade.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewService.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/infrastructure/CustomReviewRepository.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/infrastructure/ReviewReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/infrastructure/ReviewRepositoryImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/presentation/ReviewController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/presentation/ReviewDto.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/page/CustomJpaSliceInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/page/CustomPageInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/page/CustomPagingInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/page/CustomSliceInfo.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/review/application/ReviewFacadeTest.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/review/core/ReviewServiceImplTest.java
Labels: :test_tube: Test, ✏️ Fix

#437 BugFix : scrapingDate 필드 타입 변경
  module-domain/src/main/java/kernel/jdon/moduledomain/wantedjd/domain/WantedJd.java
Labels: 🐞🔨 Bugfix

#433 Test: 찜하기/취소하기, 찜 조회하기 팩토리 단위 테스트 작성
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/core/FavoriteReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/infrastructure/FavoriteFactoryImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/infrastructure/FavoriteReaderImpl.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/favorite/core/FavoriteServiceImplTest.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/favorite/infrastructure/FavoriteFactoryImplTest.java
  module-domain/src/main/java/kernel/jdon/moduledomain/skill/domain/BackendSkillType.java
  module-domain/src/main/java/kernel/jdon/moduledomain/skill/domain/FrontendSkillType.java
Labels: :test_tube: Test

#432 BugFix: 커피챗 수정, 삭제시 작성자 여부 Validation 추가
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/application/CoffeeChatFacade.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatCommand.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatService.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/error/CoffeeChatErrorCode.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatDtoMapper.java
Labels: 🐞🔨 Bugfix

#423 Feature: JD 목록조회 검색기능 구현
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatCommand.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatSortCondition.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatSortType.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatRepositoryImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatCondition.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/application/JdFacade.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdInfoMapper.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdSearchType.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdService.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdSortType.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/CustomWantedJdRepository.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/JdReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/JdReaderInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/WantedJdRepositoryImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdCondition.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdDto.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdDtoMapper.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/web/WebConfig.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/jd/application/JdFacadeTest.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/jd/core/JdServiceImplTest.java
Labels: :sparkles: Feature, :test_tube: Test

#440 Docs: 새 기능에 대한 readme 설명 추가
  README.md
  docs/images/jdon-coffeechat-detail.png
  docs/images/jdon-coffeechat.png
  docs/images/jdon-jd-detail.png
  docs/images/jdon-jd.png
  docs/images/jdon-login.png
  docs/images/jdon-main.png
  docs/images/jdon-my.png
  docs/images/jdon-skill-search.png
  docs/images/jdon_coffeechat_detail.png
  docs/images/jdon_coffeechat_list.png
  docs/images/jdon_login_page.png
  docs/images/jdon_main_page.png
  docs/images/jdon_my_page.png
  docs/images/jdon_search_page.png
Labels: 📑 Docs

#446 Chore: module-batch 모듈 생성
  module-batch/build.gradle
  module-batch/gradle/wrapper/gradle-wrapper.jar
  module-batch/gradle/wrapper/gradle-wrapper.properties
  module-batch/gradlew
  module-batch/gradlew.bat
  module-batch/src/main/java/kernel/jdon/modulebatch/ModuleBatchApplication.java
  module-batch/src/main/resources/application.yml
  module-batch/src/main/resources/logback-spring.xml
  module-batch/src/main/resources/spy.properties
  module-batch/src/test/java/kernel/jdon/modulebatch/ModuleBatchApplicationTests.java
  settings.gradle
Labels: :green_heart: Chore

#439 Test: Skill 도메인 테스트코드 리팩토링
  module-api/src/test/java/kernel/jdon/moduleapi/domain/skill/application/SkillFacadeTest.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/skill/core/SkillServiceImplTest.java
Labels: 🔨 Refactor, :test_tube: Test

#447 Feature: actuator를 위한 spring security 설정
  module-api/src/main/java/kernel/jdon/moduleapi/domain/auth/util/CryptoManager.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/auth/util/CryptoProperties.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/auth/util/SecretKeyConstants.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/AllowOriginProperties.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/OAuth2SecurityConfig.java
  module-api/src/main/resources/application-dev.yml
  module-api/src/main/resources/application-local.yml
  module-api/src/main/resources/application-prod.yml
Labels: :sparkles: Feature

#442 Fix: OAuth2 인증 과정 중 발생할 수 있는 에러 추가
  module-api/src/main/java/kernel/jdon/moduleapi/domain/auth/core/CustomOAuth2UserServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/auth/error/AuthErrorCode.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/error/MemberErrorCode.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/JdonAuthExceptionHandler.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/LoginRedirectUrlProperties.java
  module-api/src/main/resources/application-dev.yml
  module-api/src/main/resources/application-local.yml
  module-api/src/main/resources/application-prod.yml
  module-domain/src/main/java/kernel/jdon/moduledomain/member/domain/Member.java
Labels: ✏️ Fix

#449 Feature: keyword 연관어 테이블로 관리하도록 변경
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/WantedJdRepositoryImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/SkillInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/SkillReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/SkillServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/inflearnjd/InflearnJdSkillReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/keyword/SkillKeywordReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/wantedjd/WantedJdSkillReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/error/SkillErrorCode.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/CustomSkillRepository.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillKeywordManager.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillRepositoryImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/inflearnjd/InflearnJdSkillReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/keyword/SkillKeywordReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/keyword/SkillKeywordRepository.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/wantedjd/WantedJdSkillReaderImpl.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/skill/core/SkillServiceImplTest.java
  module-domain/src/main/java/kernel/jdon/moduledomain/skill/domain/BackendSkillType.java
  module-domain/src/main/java/kernel/jdon/moduledomain/skill/domain/FrontendSkillType.java
  module-domain/src/main/java/kernel/jdon/moduledomain/skill/domain/Skill.java
  module-domain/src/main/java/kernel/jdon/moduledomain/skill/domain/SkillType.java
  module-domain/src/main/java/kernel/jdon/moduledomain/skillkeyword/domain/SkillKeyword.java
  module-domain/src/main/java/kernel/jdon/moduledomain/skillkeyword/repository/SkillKeywordDomainRepository.java
Labels: :sparkles: Feature, 🔨 Refactor

#459 Fix: 개발 서버의 oauth2 redirect 주소 변경하기
  module-api/src/main/resources/application-dev.yml
Labels: ✏️ Fix

#461 Fix: 기술스택 연관어 목록으로 검색하도록 수정
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/CustomWantedJdRepository.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/JdReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/WantedJdRepositoryImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdCondition.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/SkillReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/SkillServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/inflearnjd/InflearnJdSkillReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/keyword/SkillKeywordReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/wantedjd/WantedJdSkillReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/CustomSkillRepository.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillRepositoryImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/inflearnjd/InflearnJdSkillReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/keyword/SkillKeywordReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/keyword/SkillKeywordRepository.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/wantedjd/WantedJdSkillReaderImpl.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/jd/core/JdServiceImplTest.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/skill/core/SkillServiceImplTest.java
Labels: :test_tube: Test, ✏️ Fix

#457 Fix: 오픈채팅 URL Validation 카카오톡 기준으로 변경
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatDto.java
Labels: ✏️ Fix

#465 Feature: 개발 서버 ci-cd 구축
  .github/workflows/dev-cicd.yml
  module-api/src/test/java/kernel/jdon/moduleapi/domain/coffeechat/application/CoffeeChatApplyFacadeTest.java
  module-api/src/test/resources/application.yml
Labels: 🌏 Deploy

#469 Bugfix: 기술스택 기반 인프런 강의 SQL 중복제거 조건 추가
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillRepositoryImpl.java
Labels: 🐞🔨 Bugfix

#473 Deploy: 3월 3주차 정기배포
  .github/workflows/dev-cicd.yml
  .github/workflows/prod-cicd.yml
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatDto.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/CustomWantedJdRepository.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/JdReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/WantedJdRepositoryImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdCondition.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/SkillReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/SkillServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/inflearnjd/InflearnJdSkillReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/keyword/SkillKeywordReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/wantedjd/WantedJdSkillReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/CustomSkillRepository.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillRepositoryImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/inflearnjd/InflearnJdSkillReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/keyword/SkillKeywordReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/keyword/SkillKeywordRepository.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/wantedjd/WantedJdSkillReaderImpl.java
  module-api/src/main/resources/application-dev.yml
  module-api/src/main/resources/application-local.yml
  module-api/src/main/resources/application-prod.yml
  module-api/src/test/java/kernel/jdon/moduleapi/domain/coffeechat/application/CoffeeChatApplyFacadeTest.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/jd/core/JdServiceImplTest.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/skill/core/SkillServiceImplTest.java
  module-api/src/test/resources/application.yml
Labels: 🌏 Deploy

#477 test: test cicd for secret enviroment
  .github/workflows/dev-cicd.yml
Labels: 🌏 Deploy

#479 Fix: 원티드 채용공고 스크래핑 항목에 마감일자 항목 추가
  module-crawler/src/main/java/kernel/jdon/modulecrawler/wanted/dto/response/WantedJobDetailResponse.java
Labels: ✏️ Fix

#482 Fix: oauth2 인증 중 error 처리 로직과 ci-cd event trigger 수정
  .github/workflows/dev-cicd.yml
  module-api/src/main/java/kernel/jdon/moduleapi/domain/auth/infrastructure/KakaoOAuth2StrategyImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/JdonAuthExceptionHandler.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/JdonOAuth2AuthenticationSuccessHandler.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/OAuth2SecurityConfig.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/properties/AllowOriginProperties.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/properties/LoginRedirectUrlProperties.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/properties/WithdrawProperties.java
Labels: 🌏 Deploy, 🔨 Refactor

#484 Fix: WantedJdActiveStatus `ALWAYS` 상수 추가
  module-crawler/src/main/java/kernel/jdon/modulecrawler/wanted/dto/response/WantedJobDetailResponse.java
  module-domain/src/main/java/kernel/jdon/moduledomain/wantedjd/domain/WantedJdActiveStatus.java
Labels: ✏️ Fix

#486 Fix: WantedJd 생성 로직 캡슐화
  module-crawler/src/main/java/kernel/jdon/modulecrawler/wanted/dto/response/WantedJobDetailResponse.java
  module-domain/src/main/java/kernel/jdon/moduledomain/wantedjd/domain/WantedJd.java
Labels: ✏️ Fix

#495 Fix: RestTemplate Timeout 설정
  module-crawler/build.gradle
  module-crawler/src/main/java/kernel/jdon/modulecrawler/config/AppConfig.java
  module-crawler/src/main/java/kernel/jdon/modulecrawler/config/RestTemplateConfig.java
  module-crawler/src/main/java/kernel/jdon/modulecrawler/global/error/code/CrawlerServerErrorCode.java
  module-crawler/src/main/java/kernel/jdon/modulecrawler/global/error/exception/BaseThrowException.java
  module-crawler/src/main/java/kernel/jdon/modulecrawler/global/error/exception/CrawlerException.java
Labels: ✏️ Fix

#496 Chore: BaseThrowException common 모듈로 이동
  module-api/src/main/java/kernel/jdon/moduleapi/domain/auth/error/AuthErrorCode.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/error/CoffeeChatErrorCode.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/error/FaqErrorCode.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/error/FavoriteErrorCode.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/inflearncourse/error/InflearncourseErrorCode.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/error/JdErrorCode.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jobcategory/error/JobCategoryErrorCode.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/error/MemberErrorCode.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/error/ReviewErrorCode.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/error/SkillErrorCode.java
  module-common/src/main/java/kernel/jdon/modulecommon/error/BaseThrowException.java
  module-crawler/src/main/java/kernel/jdon/modulecrawler/global/error/code/CrawlerServerErrorCode.java
  module-crawler/src/main/java/kernel/jdon/modulecrawler/global/error/exception/BaseThrowException.java
Labels: :green_heart: Chore

#492 Feature: 전체 원티드 채용공고 스크래핑 배치 구축
  module-batch/build.gradle
  module-batch/src/main/java/kernel/jdon/ModuleBatchApplication.java
  module-batch/src/main/java/kernel/jdon/modulebatch/domain/jobcategory/error/JobCategoryErrorCode.java
  module-batch/src/main/java/kernel/jdon/modulebatch/domain/jobcategory/repository/JobCategoryRepository.java
  module-batch/src/main/java/kernel/jdon/modulebatch/domain/skill/error/SkillErrorCode.java
  module-batch/src/main/java/kernel/jdon/modulebatch/domain/skill/repository/SkillRepository.java
  module-batch/src/main/java/kernel/jdon/modulebatch/domain/skillhistory/repository/SkillHistoryRepository.java
  module-batch/src/main/java/kernel/jdon/modulebatch/domain/wantedjd/repository/WantedJdRepository.java
  module-batch/src/main/java/kernel/jdon/modulebatch/domain/wantedjdskill/repository/WantedJdSkillRepository.java
  module-batch/src/main/java/kernel/jdon/modulebatch/global/condition/SearchCondition.java
  module-batch/src/main/java/kernel/jdon/modulebatch/global/config/RestTemplateConfig.java
  module-batch/src/main/java/kernel/jdon/modulebatch/global/config/ScrapingWantedProperties.java
  module-batch/src/main/java/kernel/jdon/modulebatch/global/exception/BatchException.java
  module-batch/src/main/java/kernel/jdon/modulebatch/global/exception/BatchServerErrorCode.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/AllWantedJobScrapingJobConfig.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/reader/BackendWantedJdItemReader.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/reader/FrontendWantedJdItemReader.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/reader/WantedJdClient.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/reader/condition/JobSearchExperience.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/reader/condition/JobSearchJobCategory.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/reader/condition/JobSearchJobPosition.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/reader/condition/JobSearchLocation.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/reader/condition/JobSearchSort.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/reader/dto/WantedJobDetailListResponse.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/reader/dto/WantedJobDetailResponse.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/reader/dto/WantedJobListResponse.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/reader/fetchmanager/JobDetailFetchManager.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/reader/fetchmanager/JobListFetchManager.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/writer/WantedJdItemWriter.java
  module-batch/src/main/java/kernel/jdon/modulebatch/listener/AllWantedJobScrapingJobListener.java
  module-batch/src/main/resources/application.yml
  module-domain/src/main/java/kernel/jdon/moduledomain/base/AbstractEntity.java
  module-domain/src/main/java/kernel/jdon/moduledomain/wantedjd/domain/WantedJd.java
Labels: :sparkles: Feature

#498 Feat: 로그 모니터링 설정
  module-api/build.gradle
  module-api/src/main/resources/application.yml
  module-api/src/main/resources/logback-spring.xml
  module-api/src/main/resources/loki-appender.xml
  module-api/src/main/resources/stdout-appender.xml
  module-batch/src/main/java/kernel/jdon/modulebatch/ModuleBatchApplication.java
Labels: ⚙️ Settings

#508 Fix: JD 상세조회 API 마감일자 항목 추가
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdInfoMapper.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdDto.java
  module-api/src/test/java/kernel/jdon/faq/service/FaqServiceTest.java
  module-api/src/test/java/kernel/jdon/favorite/controller/FavoriteControllerTest.java
  module-common/src/main/java/kernel/jdon/modulecommon/util/DateParserUtil.java
Labels: ✏️ Fix

#509 Deploy: 3월 3주차 수시배포
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdInfoMapper.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdDto.java
  module-api/src/test/java/kernel/jdon/faq/service/FaqServiceTest.java
  module-api/src/test/java/kernel/jdon/favorite/controller/FavoriteControllerTest.java
  module-common/src/main/java/kernel/jdon/modulecommon/util/DateParserUtil.java
Labels: 🌏 Deploy

#501 Feature: 인프런 크롤링 배치
  module-batch/build.gradle
  module-batch/src/main/java/kernel/jdon/modulebatch/ModuleBatchApplication.java
  module-batch/src/main/java/kernel/jdon/modulebatch/domain/inflearncourse/error/InflearnErrorCode.java
  module-batch/src/main/java/kernel/jdon/modulebatch/domain/inflearncourse/repository/InflearnCourseRepository.java
  module-batch/src/main/java/kernel/jdon/modulebatch/domain/inflearnjdskill/repository/InflearnJdSkillRepository.java
  module-batch/src/main/java/kernel/jdon/modulebatch/domain/skill/BackendSkillType.java
  module-batch/src/main/java/kernel/jdon/modulebatch/domain/skill/FrontendSkillType.java
  module-batch/src/main/java/kernel/jdon/modulebatch/domain/skill/SkillType.java
  module-batch/src/main/java/kernel/jdon/modulebatch/domain/skill/repository/SkillRepository.java
  module-batch/src/main/java/kernel/jdon/modulebatch/global/config/ScrapingInflearnProperties.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/course/InflearnCourseScrapingJobConfig.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/course/dto/InflearnCourseAndSkillKeywordInfo.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/course/listener/InflearnJobExecutionListener.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/course/processor/InflearnCourseClient.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/course/processor/InflearnCourseItemProcessor.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/course/processor/condition/CourseDomain.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/course/processor/condition/CourseSearchSort.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/course/processor/condition/DevelopmentProgrammingCategory.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/course/processor/service/CourseKeywordAnalyzer.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/course/processor/service/CourseParser.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/course/processor/service/CourseScraper.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/course/processor/service/converter/EntityConverter.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/course/processor/service/converter/KeywordTranslator.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/course/processor/service/converter/SkillStandardizer.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/course/processor/service/manager/DynamicSleepTimeManager.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/course/processor/service/manager/InflearnCourseCounter.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/course/processor/service/manager/LastPageDiscriminator.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/course/reader/InflearnCourseItemReader.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/course/writer/InflearnCourseItemWriter.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/course/writer/service/CourseStorer.java
  module-batch/src/main/java/kernel/jdon/modulebatch/scheduler/InflearnScheduler.java
Labels: :sparkles: Feature

#512 Hotfix: DateParserUtil localDateTimeToDateString 날짜 처리 수정
  module-common/src/main/java/kernel/jdon/modulecommon/util/DateParserUtil.java
Labels: 🐞🔨 Bugfix

#515 Fix: 인프런 크롤링 스케줄러
  module-batch/src/main/java/kernel/jdon/modulebatch/job/course/InflearnCourseScrapingJobConfig.java
  module-batch/src/main/java/kernel/jdon/modulebatch/scheduler/InflearnScheduler.java
Labels: ✏️ Fix

#518 Feature: API 모듈 Slack 웹훅 추가
  module-api/build.gradle
  module-api/src/main/resources/application-dev.yml
  module-api/src/main/resources/application-local.yml
  module-api/src/main/resources/application-prod.yml
  module-api/src/main/resources/logback-spring.xml
  module-api/src/main/resources/slack-appender-dev.xml
  module-api/src/main/resources/slack-appender-prod.xml
  module-common/build.gradle
Labels: :sparkles: Feature

#503 Refactor: 기술스택 이력 및 기술스택 저장 벌크 insert로 변경하여 성능 최적화 및 스케줄러 등록
  module-batch/src/main/java/kernel/jdon/ModuleBatchApplication.java
  module-batch/src/main/java/kernel/jdon/modulebatch/domain/skillhistory/repository/JdbcSkillHistoryRepository.java
  module-batch/src/main/java/kernel/jdon/modulebatch/domain/skillhistory/repository/SkillHistoryDao.java
  module-batch/src/main/java/kernel/jdon/modulebatch/domain/wantedjdskill/repository/WantedJdSkillDto.java
  module-batch/src/main/java/kernel/jdon/modulebatch/global/exception/BatchServerErrorCode.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/AllWantedJobScrapingJobConfig.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/PartWantedJdScrapingJobConfig.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/writer/JdbcWantedJdSkillRepository.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/writer/WantedJdItemWriter.java
  module-batch/src/main/java/kernel/jdon/modulebatch/scheduler/JdScheduler.java
  module-batch/src/main/resources/application.yml
Labels: 🔨 Refactor

#522 Fix: 원티드 스크래핑 배치 스케줄링 시간 변경
  module-batch/src/main/java/kernel/jdon/modulebatch/scheduler/JdScheduler.java
Labels: ✏️ Fix

#524 Fix: health check용 api securityConfig에 권한 허용
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/OAuth2SecurityConfig.java
  module-api/src/main/resources/application-dev.yml
  module-api/src/main/resources/application-local.yml
  module-api/src/main/resources/application-prod.yml
Labels: ✏️ Fix, 👷 NO-Deploy

#531 Chore: 슬랙 알림 로그 레벨 ERROR로 수정
  module-api/src/main/resources/slack-appender-dev.xml
  module-api/src/main/resources/slack-appender-prod.xml
Labels: :green_heart: Chore

#536 Chore: slack-appender 오타 수정
  module-batch/src/main/resources/slack-appender-dev.xml
  module-batch/src/main/resources/slack-appender-prod.xml
Labels: ✏️ Fix

#537 Chore: slack-appender 오타 수정 (#536)
  module-batch/src/main/resources/slack-appender-dev.xml
  module-batch/src/main/resources/slack-appender-prod.xml
Labels: :green_heart: Chore

#538 Fix: 검색 키워드 길이 제한 validation 추가
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/presentation/SkillController.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/exception/GlobalExceptionHandler.java
Labels: ✏️ Fix

#539 Feature: 슬랙 알림 전송 기능 구현
  module-api/src/main/java/kernel/jdon/ModuleApiApplication.java
  module-batch/src/main/java/kernel/jdon/ModuleBatchApplication.java
  module-batch/src/main/java/kernel/jdon/modulebatch/scheduler/JdScheduler.java
  module-batch/src/main/resources/slack-appender-dev.xml
  module-batch/src/main/resources/slack-appender-prod.xml
  module-common/build.gradle
  module-common/src/main/java/kernel/jdon/modulecommon/slack/SlackMessage.java
  module-common/src/main/java/kernel/jdon/modulecommon/slack/SlackSender.java
Labels: :sparkles: Feature

#541 Chore: logback-slack-appender 의존성 추가
  module-common/build.gradle
Labels: :green_heart: Chore

#540 3월 3주차 수시배포 3
  module-api/src/main/java/kernel/jdon/ModuleApiApplication.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/presentation/SkillController.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/exception/GlobalExceptionHandler.java
  module-batch/src/main/java/kernel/jdon/ModuleBatchApplication.java
  module-batch/src/main/java/kernel/jdon/modulebatch/scheduler/JdScheduler.java
  module-batch/src/main/resources/slack-appender-dev.xml
  module-batch/src/main/resources/slack-appender-prod.xml
  module-common/build.gradle
  module-common/src/main/java/kernel/jdon/modulecommon/slack/SlackMessage.java
  module-common/src/main/java/kernel/jdon/modulecommon/slack/SlackSender.java
Labels: 🌏 Deploy

#545 3월 3주차 수시배포
  module-batch/src/main/java/kernel/jdon/modulebatch/domain/wantedjd/repository/WantedJdRepository.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/AllWantedJobScrapingJobConfig.java
Labels: 🌏 Deploy

#549 Docs: README 서비스 소개 gif /아키텍처 추가
  README.md
Labels: 📑 Docs, 👷 NO-Deploy

#543 Feature: 커피챗 만료처리 스케쥴링 적용
  module-batch/src/main/java/kernel/jdon/modulebatch/domain/coffeechat/repository/CoffeeChatRepository.java
  module-batch/src/main/java/kernel/jdon/modulebatch/scheduler/CoffeeChatScheduler.java
Labels: :sparkles: Feature

#553 fix: 커피챗 만료 스케쥴링 매 30분마다 실행하도록 변경
  module-batch/src/main/java/kernel/jdon/modulebatch/scheduler/CoffeeChatScheduler.java
Labels: ✏️ Fix

#550 Feature: Job, Step 실행 및 종료 슬랙 알림 설정
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/AllWantedJobScrapingJobConfig.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/PartWantedJdScrapingJobConfig.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/listener/AllBackendWantedJobScrapingJStepListener.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/listener/AllFrontWantedJobScrapingJStepListener.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/listener/AllWantedJobScrapingJobListener.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/listener/PartBackendWantedJobScrapingJStepListener.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/listener/PartFrontWantedJobScrapingJStepListener.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/listener/PartWantedJobScrapingJobListener.java
  module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/listener/UpdateJdStatusStepListener.java
  module-batch/src/main/java/kernel/jdon/modulebatch/scheduler/JdScheduler.java
  module-common/src/main/java/kernel/jdon/modulecommon/slack/SlackSender.java
Labels: :sparkles: Feature
