Repository Kernel360/f1-JDON-Backend, pull requests merged in 2024-01, with the labels that each got.

#63 BugFix: skill, job_category 테이블 수정
  module-domain/src/main/java/kernel/jdon/jobcategory/domain/JobCategory.java
  module-domain/src/main/java/kernel/jdon/skill/domain/Skill.java
Labels: 🐞🔨 Bugfix

#71 Refactor: 커피챗과 멤버 엔터티 필드 및 제약조건 수정
  module-domain/src/main/java/kernel/jdon/coffeechat/domain/CoffeeChat.java
  module-domain/src/main/java/kernel/jdon/member/domain/Member.java
Labels: 🔨 Refactor

#72 Feature: 원티드 jd 스크래핑 구현
  module-common/src/main/java/kernel/jdon/util/StringUtil.java
  module-crawler/src/main/java/kernel/jdon/config/AppConfig.java
  module-crawler/src/main/java/kernel/jdon/config/UrlConfig.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/.gitkeep
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/controller/WantedCrawlerController.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/converter/EntityConverter.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/dto/object/CreateSkillDto.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/dto/response/WantedJobDetailResponse.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/dto/response/WantedJobListResponse.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/repository/JobCategoryRepository.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/repository/SkillRepository.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/repository/WantedJdRepository.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/repository/WantedJdSkillRepository.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/search/JobSearchCondition.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/search/JobSearchExperience.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/search/JobSearchJobCategory.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/search/JobSearchJobPosition.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/search/JobSearchLocation.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/search/JobSearchSort.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/service/WantedCrawlerService.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/vo/SkillVo.java
  module-crawler/src/main/resources/url.properties
  module-domain/src/main/java/kernel/jdon/jobcategory/domain/JobCategory.java
  module-domain/src/main/java/kernel/jdon/skill/domain/Skill.java
  module-domain/src/main/java/kernel/jdon/wanted/domain/WantedJd.java
  module-domain/src/main/java/kernel/jdon/wantedskill/domain/WantedJdSkill.java
Labels: :sparkles: Feature

#76 Feature: 가데이터 반환 Skill API 구현
  module-api/src/main/java/kernel/jdon/skill/controller/SkillController.java
  module-api/src/test/resources/application.yml
  module-domain/src/main/java/kernel/jdon/skill/dto/FindHotSkillResponse.java
  module-domain/src/main/java/kernel/jdon/skill/dto/FindJdResponse.java
  module-domain/src/main/java/kernel/jdon/skill/dto/FindJobCategorySkillResponse.java
  module-domain/src/main/java/kernel/jdon/skill/dto/FindLectureResponse.java
  module-domain/src/main/java/kernel/jdon/skill/dto/FindListDataBySkillResponse.java
  module-domain/src/main/java/kernel/jdon/skill/dto/FindListHotSkillResponse.java
  module-domain/src/main/java/kernel/jdon/skill/dto/FindListJobCategorySkillResponse.java
  module-domain/src/main/java/kernel/jdon/skill/dto/FindListMemberSkillResponse.java
  module-domain/src/main/java/kernel/jdon/skill/dto/FindMemberSkillResponse.java
Labels: :sparkles: Feature

#79 fix: WantedJd 엔티티 복합 유니크키 설정
  module-domain/src/main/java/kernel/jdon/wanted/domain/WantedJd.java
Labels: 🐞🔨 Bugfix

#83 Create cr.yml
  .github/workflow/cr.yml
Labels: 📑 Docs

#84 BugFix: add column title, scrapingDate at WantedJd table
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/converter/EntityConverter.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/dto/response/WantedJobDetailResponse.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/service/WantedCrawlerService.java
  module-domain/src/main/java/kernel/jdon/wanted/domain/WantedJd.java
Labels: 🐞🔨 Bugfix

#86 Update cr.yml
  .github/workflow/cr.yml
Labels: 📑 Docs, 🤖 GPT-Review

#87 Update cr.yml
  .github/workflow/cr.yml
Labels: 📑 Docs, 🤖 GPT-Review

#85 Feature: 마이페이지 관련 가데이터 내려주는 API 구현
  module-api/src/main/java/kernel/jdon/member/controller/.gitkeep
  module-api/src/main/java/kernel/jdon/member/controller/MemberController.java
  module-domain/src/main/java/kernel/jdon/member/dto/.gitkeep
  module-domain/src/main/java/kernel/jdon/member/dto/request/ModifyMemberRequest.java
  module-domain/src/main/java/kernel/jdon/member/dto/request/NicknameDuplicateRequest.java
  module-domain/src/main/java/kernel/jdon/member/dto/request/SaveMemberRequest.java
  module-domain/src/main/java/kernel/jdon/member/dto/response/GetMemberResponse.java
  module-domain/src/main/java/kernel/jdon/member/dto/response/ModifyMemberResponse.java
  module-domain/src/main/java/kernel/jdon/member/dto/response/RemoveMemberResponse.java
  module-domain/src/main/java/kernel/jdon/member/dto/response/SaveMemberResponse.java
Labels: :sparkles: Feature

#81 Feature: inflearn crawling
  module-common/src/main/java/kernel/jdon/util/StringUtil.java
  module-crawler/build.gradle
  module-crawler/src/main/java/kernel/jdon/config/UrlConfig.java
  module-crawler/src/main/java/kernel/jdon/crawler/common/repository/SkillRepository.java
  module-crawler/src/main/java/kernel/jdon/crawler/common/repository/WantedJdSkillRepository.java
  module-crawler/src/main/java/kernel/jdon/crawler/common/search/SearchCondition.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/.gitkeep
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/controller/InflearnCrawlerController.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/converter/EntityConverter.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/dto/CourseAndSkillsDto.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/repository/InflearnCourseRepository.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/repository/InflearnJdSkillRepository.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/search/CourseDomain.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/search/CourseSearchSort.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/search/DevelopmentProgrammingCategory.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/CourseDuplicationCheckerService.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/CourseParserService.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/CourseScraperService.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/CourseStorageService.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/CrawlerService.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/InflearnCrawlerService.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/util/SkillStandardizer.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/controller/WantedCrawlerController.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/search/JobSearchCondition.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/search/JobSearchExperience.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/search/JobSearchJobCategory.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/search/JobSearchJobPosition.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/search/JobSearchLocation.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/search/JobSearchSort.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/service/WantedCrawlerService.java
  module-crawler/src/test/resources/application.yml
  module-domain/src/main/java/kernel/jdon/inflearn/domain/InflearnCourse.java
  module-domain/src/main/java/kernel/jdon/inflearnJdskill/domain/InflearnJdSkill.java
  module-domain/src/main/java/kernel/jdon/skill/domain/Skill.java
Labels: :sparkles: Feature, 💬 Gpt Review

#93 Feature: 커피챗 등록, 상세조회 API 구현
  module-api/src/main/java/kernel/jdon/coffeechat/.gitkeep
  module-api/src/main/java/kernel/jdon/coffeechat/controller/CoffeeChatController.java
  module-api/src/main/java/kernel/jdon/coffeechat/repository/CoffeeChatRepository.java
  module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatService.java
  module-common/src/main/java/kernel/jdon/error/code/CoffeeChatErrorCode.java
  module-domain/src/main/java/kernel/jdon/coffeechat/domain/CoffeeChat.java
  module-domain/src/main/java/kernel/jdon/coffeechat/dto/request/CreateCoffeeChatRequest.java
  module-domain/src/main/java/kernel/jdon/coffeechat/dto/response/CreateCoffeeChatResponse.java
  module-domain/src/main/java/kernel/jdon/coffeechat/dto/response/FindCoffeeChatResponse.java
  module-domain/src/main/java/kernel/jdon/member/domain/Member.java
Labels: :sparkles: Feature

#94 Feature: add dummy data for favorite inflearn lecture api
  module-api/src/main/java/kernel/jdon/favorite/.gitkeep
  module-api/src/main/java/kernel/jdon/favorite/controller/FavoriteController.java
  module-domain/src/main/java/kernel/jdon/favorite/domain/dto/request/CreateFavoriteRequest.java
  module-domain/src/main/java/kernel/jdon/favorite/domain/dto/response/CreateFavoriteResponse.java
  module-domain/src/main/java/kernel/jdon/favorite/domain/dto/response/FindFavoriteResponse.java
Labels: :sparkles: Feature, 💬 Gpt Review

#98 Fix: Apply feedback from code review
  module-common/src/main/java/kernel/jdon/error/code/crawler/WantedErrorCode.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/service/WantedCrawlerService.java
  module-domain/src/main/java/kernel/jdon/skill/domain/Skill.java
Labels: ✏️ Fix

#100 Feature: 커피챗 수정 API 구현
  module-api/src/main/java/kernel/jdon/coffeechat/controller/CoffeeChatController.java
  module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatService.java
  module-common/src/main/java/kernel/jdon/error/code/api/CoffeeChatErrorCode.java
  module-domain/build.gradle
  module-domain/src/main/java/kernel/jdon/coffeechat/domain/CoffeeChat.java
Labels: :sparkles: Feature, ⚙️ Settings, 💬 Gpt Review

#113 Feature: add dummy data for finding companies by skill api
  module-api/src/main/java/kernel/jdon/skill/controller/SkillController.java
  module-domain/src/main/java/kernel/jdon/skill/dto/FindCompanyBySkillResponse.java
  module-domain/src/main/java/kernel/jdon/skill/dto/FindListCompanyBySkillResponse.java
Labels: :sparkles: Feature

#114 Feature: 커피챗 삭제 API 구현
  module-api/src/main/java/kernel/jdon/coffeechat/controller/CoffeeChatController.java
  module-api/src/main/java/kernel/jdon/coffeechat/repository/CoffeeChatRepository.java
  module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatService.java
  module-domain/src/main/java/kernel/jdon/coffeechat/domain/CoffeeChat.java
Labels: :sparkles: Feature

#119 Chore: 모듈 별 repository 파일 domain 모듈로 통합
  module-api/src/main/java/kernel/jdon/inflearncourse/.gitkeep
  module-api/src/main/java/kernel/jdon/wantedjd/.gitkeep
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/converter/EntityConverter.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/dto/CourseAndSkillsDto.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/CourseDuplicationCheckerService.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/CourseParserService.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/CourseStorageService.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/InflearnCrawlerService.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/converter/EntityConverter.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/service/WantedCrawlerService.java
  module-domain/src/main/java/kernel/jdon/coffeechat/repository/CoffeeChatRepository.java
  module-domain/src/main/java/kernel/jdon/coffeechatmember/repository/.gitkeep
  module-domain/src/main/java/kernel/jdon/faq/repository/FaqRepository.java
  module-domain/src/main/java/kernel/jdon/favorite/domain/Favorite.java
  module-domain/src/main/java/kernel/jdon/favorite/repository/.gitkeep
  module-domain/src/main/java/kernel/jdon/inflearncourse/domain/InflearnCourse.java
  module-domain/src/main/java/kernel/jdon/inflearncourse/repository/InflearnCourseRepository.java
  module-domain/src/main/java/kernel/jdon/inflearnjdskill/domain/InflearnJdSkill.java
  module-domain/src/main/java/kernel/jdon/inflearnjdskill/repository/InflearnJdSkillRepository.java
  module-domain/src/main/java/kernel/jdon/jobcategory/repository/JobCategoryRepository.java
  module-domain/src/main/java/kernel/jdon/member/repository/.gitkeep
  module-domain/src/main/java/kernel/jdon/memberskill/repository/.gitkeep
  module-domain/src/main/java/kernel/jdon/wantedjd/domain/WantedJd.java
  module-domain/src/main/java/kernel/jdon/wantedjd/repository/.gitkeep
  module-domain/src/main/java/kernel/jdon/wantedjd/repository/WantedJdRepository.java
  module-domain/src/main/java/kernel/jdon/wantedskill/domain/WantedJdSkill.java
  module-domain/src/main/java/kernel/jdon/wantedskill/repository/.gitkeep
Labels: :green_heart: Chore

#120 Setting: querydsl 환경설정
  module-api/src/main/java/kernel/jdon/wantedjdskill/.gitkeep
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/converter/EntityConverter.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/CourseStorageService.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/converter/EntityConverter.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/service/WantedCrawlerService.java
  module-domain/build.gradle
  module-domain/src/main/java/kernel/jdon/config/QuerydslConfig.java
  module-domain/src/main/java/kernel/jdon/inflearnjdskill/domain/InflearnJdSkill.java
  module-domain/src/main/java/kernel/jdon/inflearnjdskill/repository/InflearnJdSkillRepository.java
  module-domain/src/main/java/kernel/jdon/skill/domain/Skill.java
  module-domain/src/main/java/kernel/jdon/skill/repository/SkillRepository.java
  module-domain/src/main/java/kernel/jdon/wantedjdskill/domain/WantedJdSkill.java
  module-domain/src/main/java/kernel/jdon/wantedjdskill/repository/WantedJdSkillRepository.java
  module-domain/src/main/java/kernel/jdon/wantedskill/repository/.gitkeep
Labels: ⚙️ Settings

#128 Feature: WantedJd 테이블 컬럼 추가 및 변경 사항 적용
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/controller/WantedCrawlerController.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/converter/EntityConverter.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/service/WantedCrawlerService.java
  module-domain/src/main/java/kernel/jdon/wantedjd/domain/WantedJd.java
Labels: :sparkles: Feature

#130 Refactor: common모듈 error 패키지 각 모듈로 이동 및 엔티티 리팩토링
  module-api/src/main/java/kernel/jdon/coffeechat/error/CoffeeChatErrorCode.java
  module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatService.java
  module-api/src/main/java/kernel/jdon/faq/error/FaqErrorCode.java
  module-api/src/main/java/kernel/jdon/faq/service/FaqService.java
  module-api/src/main/java/kernel/jdon/global/exception/ApiException.java
  module-api/src/main/java/kernel/jdon/global/exception/GlobalExceptionHandler.java
  module-common/src/main/java/kernel/jdon/dto/response/ErrorResponse.java
  module-common/src/main/java/kernel/jdon/error/ErrorCode.java
  module-crawler/src/main/java/kernel/jdon/crawler/config/AppConfig.java
  module-crawler/src/main/java/kernel/jdon/crawler/config/UrlConfig.java
  module-crawler/src/main/java/kernel/jdon/crawler/global/error/code/WantedErrorCode.java
  module-crawler/src/main/java/kernel/jdon/crawler/global/error/exception/CrawlerException.java
  module-crawler/src/main/java/kernel/jdon/crawler/global/error/exception/GlobalExceptionHandler.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/InflearnCrawlerService.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/service/WantedCrawlerService.java
  module-domain/build.gradle
  module-domain/src/main/java/kernel/jdon/coffeechat/domain/CoffeeChat.java
Labels: ⚙️ Settings, :green_heart: Chore

#137 Feature: 요즘 뜨는 기술 스택 조회 API 구현
  module-api/src/main/java/kernel/jdon/skill/controller/SkillController.java
  module-api/src/main/java/kernel/jdon/skill/dto/response/FindHotSkillResponse.java
  module-api/src/main/java/kernel/jdon/skill/dto/response/FindListHotSkillResponse.java
  module-api/src/main/java/kernel/jdon/skill/service/SkillService.java
  module-domain/src/main/java/kernel/jdon/skill/repository/SkillRepository.java
  module-domain/src/main/java/kernel/jdon/skill/repository/SkillRepositoryCustom.java
  module-domain/src/main/java/kernel/jdon/skill/repository/SkillRepositoryImpl.java
Labels: :sparkles: Feature

#136 Feature: OAuth2를 이용하여 사용자 정보를 받고, 로그인 유저정보를 세션에 저장하는 로직 구현
  module-api/build.gradle
  module-api/src/main/java/kernel/jdon/auth/controller/AuthController.java
  module-api/src/main/java/kernel/jdon/auth/controller/OAuthController.java
  module-api/src/main/java/kernel/jdon/auth/dto/JdonOAuth2User.java
  module-api/src/main/java/kernel/jdon/auth/dto/SessionUserInfo.java
  module-api/src/main/java/kernel/jdon/auth/encrypt/AesUtil.java
  module-api/src/main/java/kernel/jdon/auth/encrypt/HmacUtil.java
  module-api/src/main/java/kernel/jdon/auth/encrypt/SecretKeyConstants.java
  module-api/src/main/java/kernel/jdon/auth/error/AuthErrorCode.java
  module-api/src/main/java/kernel/jdon/auth/service/JdonOAuth2UserService.java
  module-api/src/main/java/kernel/jdon/auth/service/LoginUserArgumentResolver.java
  module-api/src/main/java/kernel/jdon/config/OAuth2SecurityConfig.java
  module-api/src/main/java/kernel/jdon/config/WebConfig.java
  module-api/src/main/java/kernel/jdon/global/annotation/LoginUser.java
  module-api/src/main/java/kernel/jdon/jobcategory/.gitkeep
  module-api/src/main/java/kernel/jdon/jobcategory/repository/JobCategoryRepository.java
  module-api/src/main/java/kernel/jdon/member/controller/MemberController.java
  module-api/src/main/java/kernel/jdon/member/service/.gitkeep
  module-api/src/main/java/kernel/jdon/member/service/MemberService.java
  module-api/src/main/resources/application.yml
  module-common/src/main/java/kernel/jdon/error/code/api/MemberErrorCode.java
  module-domain/src/main/java/kernel/jdon/auth/dto/object/RegisterMemberDto.java
  module-domain/src/main/java/kernel/jdon/auth/dto/request/RegisterRequest.java
  module-domain/src/main/java/kernel/jdon/auth/dto/response/RegisterResponse.java
  module-domain/src/main/java/kernel/jdon/auth/dto/response/WithdrawResponse.java
  module-domain/src/main/java/kernel/jdon/member/domain/Gender.java
  module-domain/src/main/java/kernel/jdon/member/domain/Member.java
  module-domain/src/main/java/kernel/jdon/member/domain/MemberAccountStatus.java
  module-domain/src/main/java/kernel/jdon/member/domain/SocialProviderType.java
  module-domain/src/main/java/kernel/jdon/member/repository/.gitkeep
  module-domain/src/main/java/kernel/jdon/member/repository/MemberRepository.java
  module-domain/src/main/java/kernel/jdon/memberskill/domain/MemberSkill.java
  module-domain/src/main/java/kernel/jdon/memberskill/repository/.gitkeep
  module-domain/src/main/java/kernel/jdon/memberskill/repository/MemberSkillRepository.java
Labels: :sparkles: Feature

#133 Feature: Github OAuth2 구현하기
  module-api/src/main/java/kernel/jdon/auth/JdonOAuth2User.java
  module-api/src/main/java/kernel/jdon/auth/service/JdonOAuth2UserService.java
  module-api/src/main/java/kernel/jdon/member/controller/MemberController.java
  module-api/src/main/resources/application.yml
  module-domain/src/main/java/kernel/jdon/skill/repository/SkillRepositoryCustom.java
Labels: :sparkles: Feature

#140 Feature: 내 정보 조회하는 API 구현
  module-api/src/main/java/kernel/jdon/member/controller/MemberController.java
  module-api/src/main/java/kernel/jdon/member/dto/response/FindMemberResponse.java
  module-api/src/main/java/kernel/jdon/member/dto/response/GetMemberResponse.java
  module-api/src/main/java/kernel/jdon/member/service/MemberService.java
  module-common/src/main/java/kernel/jdon/error/code/api/MemberErrorCode.java
  module-domain/src/main/java/kernel/jdon/memberskill/domain/MemberSkill.java
Labels: :sparkles: Feature

#141 Feature: 내 정보 수정하는 API 구현
  module-api/src/main/java/kernel/jdon/member/controller/MemberController.java
  module-api/src/main/java/kernel/jdon/member/dto/request/ModifyMemberRequest.java
  module-api/src/main/java/kernel/jdon/member/dto/request/UpdateMemberRequest.java
  module-api/src/main/java/kernel/jdon/member/dto/response/ModifyMemberResponse.java
  module-api/src/main/java/kernel/jdon/member/dto/response/UpdateMemberResponse.java
  module-api/src/main/java/kernel/jdon/member/service/MemberService.java
  module-common/src/main/java/kernel/jdon/error/code/api/JobCategoryErrorCode.java
  module-common/src/main/java/kernel/jdon/error/code/api/MemberErrorCode.java
  module-common/src/main/java/kernel/jdon/error/code/api/SkillErrorCode.java
  module-domain/src/main/java/kernel/jdon/member/domain/Member.java
Labels: :sparkles: Feature

#144 Feature: 닉네임 중복 확인하는 API 구현
  module-api/src/main/java/kernel/jdon/member/controller/MemberController.java
  module-api/src/main/java/kernel/jdon/member/service/MemberService.java
  module-common/src/main/java/kernel/jdon/error/code/api/MemberErrorCode.java
  module-domain/src/main/java/kernel/jdon/member/repository/MemberRepository.java
Labels: :sparkles: Feature

#147 Test: 커피챗 컨트롤러 단위테스트 작성
  module-api/build.gradle
  module-api/src/main/java/kernel/jdon/coffeechat/dto/request/CreateCoffeeChatRequest.java
  module-api/src/main/java/kernel/jdon/coffeechat/dto/request/UpdateCoffeeChatRequest.java
  module-api/src/test/java/kernel/jdon/coffeechat/controller/CoffeeChatControllerTest.java
Labels: :test_tube: Test

#143 Feature: 인프런 크롤링 리팩토링
  module-common/src/main/java/kernel/jdon/util/StringUtil.java
  module-crawler/src/main/java/kernel/jdon/crawler/global/error/code/InflearnErrorCode.java
  module-crawler/src/main/java/kernel/jdon/crawler/global/error/code/SkillErrorCode.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/controller/InflearnCrawlerController.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/converter/EntityConverter.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/converter/KeywordTranslator.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/dto/CourseAndSkillsDto.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/CourseDuplicationCheckerService.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/CourseKeywordAnalysisService.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/CourseParserService.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/CourseScraperService.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/CourseStorageService.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/CrawlerService.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/InflearnCrawlerService.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/util/InflearnCrawlerState.java
  module-domain/src/main/java/kernel/jdon/inflearncourse/repository/InflearnCourseRepository.java
  module-domain/src/main/java/kernel/jdon/inflearnjdskill/domain/InflearnJdSkill.java
  module-domain/src/main/java/kernel/jdon/inflearnjdskill/repository/InflearnJdSkillRepository.java
Labels: ✏️ Fix

#152 Fix: Q 클래스가 생성되는 문제 해결
  module-domain/build.gradle
Labels: 🐞🔨 Bugfix

#154 Feature: 로그아웃 API 구현하기
  module-api/src/main/java/kernel/jdon/config/OAuth2SecurityConfig.java
Labels: :sparkles: Feature

#162 Fix: 요즘 뜨는 기술스택 조회 API 수정
  module-api/build.gradle
  module-api/src/main/java/kernel/jdon/skill/dto/object/FindHotSkillDto.java
  module-api/src/main/java/kernel/jdon/skill/dto/response/FindListHotSkillResponse.java
  module-api/src/main/java/kernel/jdon/skill/repository/SkillRepositoryCustom.java
  module-api/src/main/java/kernel/jdon/skill/repository/SkillRepositoryImpl.java
  module-api/src/main/java/kernel/jdon/skill/service/SkillService.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/service/WantedCrawlerService.java
  module-domain/build.gradle
Labels: ✏️ Fix

#160 Feat: 공용 커스텀 페이징 응답 객체 생성
  module-api/src/main/java/kernel/jdon/global/page/CustomPageInfo.java
Labels: :sparkles: Feature

#163 Feature: 직군 별 기술 스택 조회하기 API 구현
  module-api/src/main/java/kernel/jdon/config/OAuth2SecurityConfig.java
  module-api/src/main/java/kernel/jdon/skill/controller/SkillController.java
  module-api/src/main/java/kernel/jdon/skill/dto/response/FindJobCategorySkillResponse.java
  module-api/src/main/java/kernel/jdon/skill/repository/SkillRepository.java
  module-api/src/main/java/kernel/jdon/skill/service/SkillService.java
Labels: :sparkles: Feature

#177 Feature: 직군 별 직무 조회 API 구현
  module-api/src/main/java/kernel/jdon/jobcategory/controller/JobCategoryController.java
  module-api/src/main/java/kernel/jdon/jobcategory/dto/response/FindListJobGroupResponse.java
  module-api/src/main/java/kernel/jdon/jobcategory/repository/JobCategoryRepository.java
  module-api/src/main/java/kernel/jdon/jobcategory/service/JobCategoryService.java
Labels: :sparkles: Feature

#181 Feat: 회원 맞춤 기술스택 조회 API 구현
  module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatService.java
  module-api/src/main/java/kernel/jdon/skill/controller/SkillController.java
  module-api/src/main/java/kernel/jdon/skill/dto/object/FindMemberSkillDto.java
  module-api/src/main/java/kernel/jdon/skill/dto/response/FindHotSkillResponse.java
  module-api/src/main/java/kernel/jdon/skill/dto/response/FindListMemberSkillResponse.java
  module-api/src/main/java/kernel/jdon/skill/dto/response/FindMemberSkillResponse.java
  module-api/src/main/java/kernel/jdon/skill/repository/SkillRepositoryCustom.java
  module-api/src/main/java/kernel/jdon/skill/repository/SkillRepositoryImpl.java
  module-api/src/main/java/kernel/jdon/skill/service/SkillService.java
  module-domain/src/main/java/kernel/jdon/memberskill/domain/MemberSkill.java
Labels: :sparkles: Feature

#171 Feature: 영상 찜하기 API
  module-api/src/main/java/kernel/jdon/favorite/controller/FavoriteController.java
  module-api/src/main/java/kernel/jdon/favorite/dto/request/UpdateFavoriteRequest.java
  module-api/src/main/java/kernel/jdon/favorite/dto/response/CreateFavoriteResponse.java
  module-api/src/main/java/kernel/jdon/favorite/dto/response/UpdateFavoriteResponse.java
  module-api/src/main/java/kernel/jdon/favorite/error/FavoriteErrorCode.java
  module-api/src/main/java/kernel/jdon/favorite/repository/FavoriteRepository.java
  module-api/src/main/java/kernel/jdon/favorite/service/FavoriteService.java
  module-api/src/main/java/kernel/jdon/inflearncourse/error/InflearncourseErrorCode.java
  module-api/src/main/java/kernel/jdon/inflearncourse/repository/InflearnCourseRepository.java
  module-domain/src/main/java/kernel/jdon/favorite/domain/Favorite.java
Labels: :sparkles: Feature

#185 Feature: 내가 개설한 커피챗 목록 조회 API
  module-api/src/main/java/kernel/jdon/coffeechat/controller/CoffeeChatController.java
  module-api/src/main/java/kernel/jdon/coffeechat/dto/response/FindCoffeeChatListResponse.java
  module-api/src/main/java/kernel/jdon/coffeechat/repository/CoffeeChatRepository.java
  module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatService.java
  module-api/src/main/java/kernel/jdon/favorite/service/FavoriteService.java
  module-api/src/main/java/kernel/jdon/global/page/CustomPageInfo.java
  module-api/src/main/java/kernel/jdon/global/page/CustomPageResponse.java
  module-api/src/main/resources/application.yml
Labels: :sparkles: Feature

#193 Refactor : CustomPageResponse 정적 팩토리 메서드 추가
  module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatService.java
  module-api/src/main/java/kernel/jdon/global/page/CustomPageResponse.java
Labels: 🔨 Refactor

#184 Bugfix: 영상 찜하기 API 이미 찜한 강의 새로 생성되는 문제 해결
  module-api/src/main/java/kernel/jdon/favorite/service/FavoriteService.java
Labels: 🐞🔨 Bugfix

#197 Fix: cors 허용 origin에 프론트 배포 주소 추가
  module-api/src/main/java/kernel/jdon/config/auth/OAuth2SecurityConfig.java
Labels: 🐞🔨 Bugfix

#200 Bug: skill_history 테이블 유니크 인덱스 키 삭제
  module-domain/src/main/java/kernel/jdon/skillhistory/domain/SkillHistory.java
Labels: 🐞 Bug

#182 Feature: 내가 찜한 목록 조회하기 API
  module-api/build.gradle
  module-api/src/main/java/kernel/jdon/favorite/controller/FavoriteController.java
  module-api/src/main/java/kernel/jdon/favorite/dto/request/UpdateFavoriteRequest.java
  module-api/src/main/java/kernel/jdon/favorite/dto/response/FindFavoriteResponse.java
  module-api/src/main/java/kernel/jdon/favorite/repository/FavoriteRepository.java
  module-api/src/main/java/kernel/jdon/favorite/service/FavoriteService.java
Labels: :sparkles: Feature

#215 Refactor: 원티드 스크래핑 비즈니스로직 리팩토링
  module-crawler/src/main/java/kernel/jdon/ModuleCrawlerApplication.java
  module-crawler/src/main/java/kernel/jdon/crawler/config/ScrapingInflearnConfig.java
  module-crawler/src/main/java/kernel/jdon/crawler/config/ScrapingWantedConfig.java
  module-crawler/src/main/java/kernel/jdon/crawler/config/UrlConfig.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/InflearnCrawlerService.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/dto/response/WantedJobDetailResponse.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/search/JobSearchJobPosition.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/service/WantedCrawlerService.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/service/infrastructure/JobDetailProcessingCounter.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/service/infrastructure/JobListProcessingCounter.java
  module-crawler/src/main/resources/application.yml
  module-crawler/src/main/resources/url.properties
Labels: 🔨 Refactor

#198 Feature: 커피챗 신청 API
  module-api/src/main/java/kernel/jdon/coffeechat/controller/CoffeeChatController.java
  module-api/src/main/java/kernel/jdon/coffeechat/error/CoffeeChatErrorCode.java
  module-api/src/main/java/kernel/jdon/coffeechat/repository/CoffeeChatRepository.java
  module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatService.java
  module-domain/src/main/java/kernel/jdon/coffeechat/domain/CoffeeChat.java
  module-domain/src/main/java/kernel/jdon/coffeechatmember/domain/CoffeeChatMember.java
Labels: :sparkles: Feature

#218 Fix: 커피챗 상세와 목록조회에서 누락된 항목을 포함하도록 수정
  module-api/src/main/java/kernel/jdon/coffeechat/dto/response/FindCoffeeChatListResponse.java
  module-api/src/main/java/kernel/jdon/coffeechat/dto/response/FindCoffeeChatResponse.java
Labels: ✏️ Fix

#221 Fix: 메인화면 강의데이터에 회원 별 찜 유무 항목 추가
  module-api/src/main/java/kernel/jdon/skill/controller/SkillController.java
  module-api/src/main/java/kernel/jdon/skill/dto/object/FindLectureDto.java
  module-api/src/main/java/kernel/jdon/skill/repository/SkillRepositoryCustom.java
  module-api/src/main/java/kernel/jdon/skill/repository/SkillRepositoryImpl.java
  module-api/src/main/java/kernel/jdon/skill/service/SkillService.java
Labels: ✏️ Fix

#225 Fix: userId 고정시켰던 api 일부 되돌림
  module-api/src/main/java/kernel/jdon/coffeechat/controller/CoffeeChatController.java
  module-api/src/main/java/kernel/jdon/config/auth/OAuth2SecurityConfig.java
  module-api/src/main/java/kernel/jdon/member/controller/MemberController.java
  module-api/src/main/java/kernel/jdon/skill/controller/SkillController.java
Labels: ✏️ Fix

#222 Feature: 내가 신청한 커피챗 목록 조회 API
  module-api/src/main/java/kernel/jdon/coffeechat/controller/CoffeeChatController.java
  module-api/src/main/java/kernel/jdon/coffeechat/dto/response/FindCoffeeChatResponse.java
  module-api/src/main/java/kernel/jdon/coffeechat/repository/CoffeeChatRepository.java
  module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatService.java
  module-api/src/main/java/kernel/jdon/coffeechatmember/repsitory/CoffeeChatMemberRepository.java
Labels: :sparkles: Feature

#207 Refactor: 인프런 강의 데이터 크롤링 시, enum에 있는 Skill에 대해 탐색하도록 수정
  module-api/src/main/java/kernel/jdon/favorite/service/FavoriteService.java
  module-crawler/src/main/java/kernel/jdon/crawler/config/ScrapingInflearnConfig.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/controller/InflearnCrawlerController.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/converter/KeywordTranslator.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/CourseStorageService.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/CrawlerService.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/InflearnCrawlerService.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/infrastructure/InflearnCourseCounter.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/infrastructure/LastPageDiscriminator.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/repository/SkillRepository.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/skill/BackendSkillType.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/skill/FrontendSkillType.java
  module-crawler/src/main/resources/application.yml
Labels: 🔨 Refactor

#228 Setting: fixture-monkey 라이브러리 추가
  module-api/build.gradle
Labels: ⚙️ Settings

#231 Bugfix: 개발용 배포환경을 위한 application.yml 추가
  module-api/src/main/resources/application-dev.yml
Labels: 🐞🔨 Bugfix

#226 Refactor: 불필요한 EntityConverter 클래스 제거
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/converter/EntityConverter.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/dto/object/CreateSkillDto.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/dto/response/WantedJobDetailResponse.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/service/WantedCrawlerService.java
  module-domain/src/main/java/kernel/jdon/skillhistory/domain/SkillHistory.java
Labels: 🔨 Refactor
