Repository Kernel360/f1-JDON-Backend, pull requests merged in 2024-02, with the labels that each got.

#233 BugFix: 배포 성공을 위해 application.yml 원래대로 되돌림
  module-api/src/main/java/kernel/jdon/auth/service/AuthService.java
  module-api/src/main/java/kernel/jdon/config/auth/WithdrawConfig.java
  module-api/src/main/resources/application-dev.yml
  module-api/src/main/resources/application-local.yml
  module-api/src/main/resources/application-prod.yml
  module-api/src/main/resources/application.yml
Labels: 🐞🔨 Bugfix

#235 Feature: application.yml 운영환경(local, dev, prod) 별로 분리
  module-api/src/main/java/kernel/jdon/auth/service/LoginUserArgumentResolver.java
  module-api/src/main/java/kernel/jdon/config/auth/OAuth2SecurityConfig.java
  module-api/src/main/resources/application-dev.yml
  module-api/src/main/resources/application-local.yml
  module-api/src/main/resources/application-prod.yml
  module-api/src/main/resources/application.yml
Labels: 🐞 Bug, :sparkles: Feature

#212 Refactor: 인프런 크롤링에서 동적으로 크롤링 시간 조정
  module-crawler/src/main/java/kernel/jdon/crawler/config/ScrapingInflearnConfig.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/InflearnCrawlerService.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/infrastructure/DynamicSleepTimeManager.java
  module-crawler/src/main/resources/application.yml
Labels: 🔨 Refactor

#237 BugFix: 커피챗 중복 참여신청 시 예외처리
  module-api/src/main/java/kernel/jdon/coffeechat/controller/CoffeeChatController.java
  module-api/src/main/java/kernel/jdon/coffeechat/error/CoffeeChatErrorCode.java
  module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatService.java
  module-api/src/main/java/kernel/jdon/coffeechatmember/repsitory/CoffeeChatMemberRepository.java
Labels: 🐞🔨 Bugfix

#239 Fix: cors 정책과 application.yml에 새로운 도메인 네임 적용
  module-api/src/main/java/kernel/jdon/config/auth/OAuth2SecurityConfig.java
  module-api/src/main/resources/application-dev.yml
  module-api/src/main/resources/application-prod.yml
  module-api/src/main/resources/application.yml
Labels: ✏️ Fix

#241 Fix: 인프런 강의 url 상세페이지가 담기도록 수정
  module-crawler/src/main/java/kernel/jdon/crawler/config/ScrapingInflearnConfig.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/CourseParserService.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/InflearnCrawlerService.java
  module-crawler/src/main/resources/application.yml
Labels: 🐞🔨 Bugfix

#252 Feature: 커피챗 목록조회 API 구현
  module-api/src/main/java/kernel/jdon/coffeechat/controller/CoffeeChatController.java
  module-api/src/main/java/kernel/jdon/coffeechat/dto/request/CoffeeChatCondition.java
  module-api/src/main/java/kernel/jdon/coffeechat/dto/request/CoffeeChatSortCondition.java
  module-api/src/main/java/kernel/jdon/coffeechat/dto/response/FindCoffeeChatListResponse.java
  module-api/src/main/java/kernel/jdon/coffeechat/repository/CoffeeChatRepository.java
  module-api/src/main/java/kernel/jdon/coffeechat/repository/CoffeeChatRepositoryImpl.java
  module-api/src/main/java/kernel/jdon/coffeechat/repository/CustomCoffeeChatRepository.java
  module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatService.java
  module-api/src/main/java/kernel/jdon/config/WebConfig.java
Labels: :sparkles: Feature

#249 Fix: 마지막 마지막 로그인 datetime DB에 업데이트 하도록 수정
  module-api/src/main/java/kernel/jdon/auth/service/JdonOAuth2UserService.java
  module-api/src/main/java/kernel/jdon/config/auth/JdonOAuth2AuthenticationSuccessHandler.java
  module-api/src/main/resources/application-dev.yml
  module-api/src/main/resources/application-local.yml
  module-api/src/main/resources/application-prod.yml
  module-domain/src/main/java/kernel/jdon/member/domain/Member.java
Labels: ✏️ Fix

#253 Fix: 복호화에서 발생하는 에러로 인한 status와 메시지 수정
  module-api/src/main/java/kernel/jdon/auth/controller/OAuthController.java
  module-api/src/main/java/kernel/jdon/auth/service/AuthService.java
  module-api/src/main/java/kernel/jdon/auth/service/LoginUserArgumentResolver.java
  module-api/src/main/java/kernel/jdon/member/error/MemberErrorCode.java
  module-api/src/main/java/kernel/jdon/member/service/MemberService.java
Labels: ✏️ Fix

#262 Delete .github/workflows/cr.yml
  .github/workflows/cr.yml
Labels: 📑 Docs

#260 Fix: login 없이 test를 위해서 풀어놨던 api별 권한 재설정
  module-api/src/main/java/kernel/jdon/config/auth/OAuth2SecurityConfig.java
Labels: ✏️ Fix

#264 BugFix: 커피챗 상세조회 시 응답DTO에 커피챗 개설자 식별자를 포함
  module-api/src/main/java/kernel/jdon/coffeechat/dto/response/FindCoffeeChatResponse.java
Labels: 🐞🔨 Bugfix

#261 Refactor: FaqErrorCode 리팩토링
  module-api/src/main/java/kernel/jdon/faq/error/FaqErrorCode.java
  module-api/src/main/java/kernel/jdon/faq/service/FaqService.java
  module-api/src/main/java/kernel/jdon/global/exception/BaseThrowException.java
  module-api/src/test/java/kernel/jdon/faq/service/FaqServiceTest.java
Labels: 🔨 Refactor, :test_tube: Test

#246 Refactor: 커피챗 수정 API 리팩토링
  module-api/src/main/java/kernel/jdon/coffeechat/dto/request/UpdateCoffeeChatRequest.java
  module-api/src/main/java/kernel/jdon/coffeechat/error/CoffeeChatErrorCode.java
  module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatService.java
  module-domain/src/main/java/kernel/jdon/coffeechat/domain/CoffeeChat.java
Labels: 🔨 Refactor

#265 Docs: readme 작성
  README.md
  docs/images/jdon_architecture.png
  docs/images/jdon_coffeechat_detail.png
  docs/images/jdon_coffeechat_list.png
  docs/images/jdon_erd.png
  docs/images/jdon_login_page.png
  docs/images/jdon_main_page.png
  docs/images/jdon_search_page.png
Labels: 📑 Docs

#255 Test: favorite API - 컨트롤러
  module-api/.jqwik-database
  module-api/src/main/java/kernel/jdon/favorite/dto/request/UpdateFavoriteRequest.java
  module-api/src/main/java/kernel/jdon/favorite/error/FavoriteErrorCode.java
  module-api/src/main/java/kernel/jdon/favorite/service/FavoriteService.java
  module-api/src/test/java/kernel/jdon/coffeechat/controller/CoffeeChatControllerTest.java
  module-api/src/test/java/kernel/jdon/favorite/controller/FavoriteControllerTest.java
Labels: :test_tube: Test

#263 Feature: 커피챗 동시성 제어
  module-api/build.gradle
  module-api/src/main/java/kernel/jdon/coffeechat/controller/CoffeeChatController.java
  module-api/src/main/java/kernel/jdon/coffeechat/error/CoffeeChatErrorCode.java
  module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatApplyFacade.java
  module-api/src/main/java/kernel/jdon/config/redis/CoffeeChatLockConfig.java
  module-api/src/main/java/kernel/jdon/global/exception/ApiException.java
  module-api/src/main/resources/application-dev.yml
  module-api/src/main/resources/application-local.yml
  module-api/src/main/resources/application-prod.yml
  module-api/src/test/java/kernel/jdon/moduleapi/coffeechat/controller/CoffeeChatControllerTest.java
  module-api/src/test/java/kernel/jdon/moduleapi/coffeechat/service/CoffeeChatServiceTest.java
  module-api/src/test/resources/application.yml
  module-domain/src/main/java/kernel/jdon/coffeechat/domain/CoffeeChat.java
Labels: :sparkles: Feature

#284 Bug: 커피챗 목록 조회에서 삭제된 커피챗 조회되는 현상 수정
  module-api/src/main/java/kernel/jdon/coffeechat/repository/CoffeeChatRepositoryImpl.java
Labels: 🐞 Bug

#276 Refactor: FAQ DDD 패턴 적용
  module-api/build.gradle
  module-api/src/main/java/kernel/jdon/application/faq/FaqFacade.java
  module-api/src/main/java/kernel/jdon/application/faq/FaqReader.java
  module-api/src/main/java/kernel/jdon/application/faq/FaqStore.java
  module-api/src/main/java/kernel/jdon/domain/faq/FaqCommand.java
  module-api/src/main/java/kernel/jdon/domain/faq/FaqInfo.java
  module-api/src/main/java/kernel/jdon/domain/faq/FaqService.java
  module-api/src/main/java/kernel/jdon/domain/faq/FaqServiceImpl.java
  module-api/src/main/java/kernel/jdon/faq/controller/FaqController.java
  module-api/src/main/java/kernel/jdon/faq/repository/FaqRepository.java
  module-api/src/main/java/kernel/jdon/faq/service/FaqService.java
  module-api/src/main/java/kernel/jdon/global/exception/GlobalExceptionHandler.java
  module-api/src/main/java/kernel/jdon/infrastructure/faq/FaqReaderImpl.java
  module-api/src/main/java/kernel/jdon/infrastructure/faq/FaqRepository.java
  module-api/src/main/java/kernel/jdon/infrastructure/faq/FaqStoreImpl.java
  module-api/src/main/java/kernel/jdon/interfaces/faq/FaqController.java
  module-api/src/main/java/kernel/jdon/interfaces/faq/FaqDto.java
  module-api/src/main/java/kernel/jdon/interfaces/faq/FaqDtoMapper.java
  module-common/src/main/java/kernel/jdon/dto/response/ErrorResponse.java
Labels: 🔨 Refactor

#292 Fix: redis properties yml에 추가
  module-api/src/main/resources/application-dev.yml
  module-api/src/main/resources/application-prod.yml
  module-api/src/main/resources/application.yml
Labels: ✏️ Fix

#278 Refactor: 원티드 스크래핑 비즈니스로직 리팩토링
  module-crawler/src/main/java/kernel/jdon/crawler/config/ScrapingWantedProperties.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/search/JobSearchJobPosition.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/service/WantedCrawlerService.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/service/infrastructure/JobDetailProcessingCounter.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/service/infrastructure/JobListProcessingCounter.java
Labels: 🔨 Refactor

#294 Refactor: 인기있는 기술스택 조회 API, 회원 기술 스택 조회 API 추상화 리팩토링
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/application/SkillFacade.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/SkillCommand.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/SkillInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/SkillReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/SkillService.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/SkillServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/error/SkillErrorCode.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillReaderInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillRepository.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillRepositoryCustom.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillRepositoryImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/presentation/SkillController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/presentation/SkillDto.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/presentation/SkillDtoMapper.java
  module-api/src/main/java/kernel/jdon/skill/controller/SkillController.java
  module-api/src/main/java/kernel/jdon/skill/repository/SkillRepository.java
  module-api/src/main/java/kernel/jdon/skill/repository/SkillRepositoryImpl.java
  module-api/src/main/java/kernel/jdon/skill/service/SkillService.java
  module-api/src/test/java/kernel/jdon/faq/service/FaqServiceTest.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/skill/application/SkillFacadeTest.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/skill/core/SkillServiceImplTest.java
Labels: 🔨 Refactor

#299 Fix: modulecommon 상위 패키지 추가
  module-api/src/main/java/kernel/jdon/auth/controller/AuthController.java
  module-api/src/main/java/kernel/jdon/auth/dto/AuthExceptionResponse.java
  module-api/src/main/java/kernel/jdon/auth/error/AuthErrorCode.java
  module-api/src/main/java/kernel/jdon/coffeechat/controller/CoffeeChatController.java
  module-api/src/main/java/kernel/jdon/coffeechat/error/CoffeeChatErrorCode.java
  module-api/src/main/java/kernel/jdon/faq/controller/FaqController.java
  module-api/src/main/java/kernel/jdon/faq/error/FaqErrorCode.java
  module-api/src/main/java/kernel/jdon/favorite/controller/FavoriteController.java
  module-api/src/main/java/kernel/jdon/favorite/error/FavoriteErrorCode.java
  module-api/src/main/java/kernel/jdon/inflearncourse/error/InflearncourseErrorCode.java
  module-api/src/main/java/kernel/jdon/jobcategory/controller/JobCategoryController.java
  module-api/src/main/java/kernel/jdon/jobcategory/error/JobCategoryErrorCode.java
  module-api/src/main/java/kernel/jdon/member/controller/MemberController.java
  module-api/src/main/java/kernel/jdon/member/error/MemberErrorCode.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/error/FaqErrorCode.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/presentation/FaqController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/error/SkillErrorCode.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/presentation/SkillController.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/JdonAuthExceptionHandler.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/JdonOAuth2AuthenticationSuccessHandler.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/exception/ApiException.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/exception/GlobalExceptionHandler.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/exception/UnAuthorizedException.java
  module-api/src/main/java/kernel/jdon/skill/controller/SkillController.java
  module-api/src/main/java/kernel/jdon/skill/error/SkillErrorCode.java
  module-common/src/main/java/kernel/jdon/modulecommon/dto/response/CommonResponse.java
  module-common/src/main/java/kernel/jdon/modulecommon/dto/response/ErrorResponse.java
  module-common/src/main/java/kernel/jdon/modulecommon/error/ErrorCode.java
  module-common/src/main/java/kernel/jdon/modulecommon/log/LoggingForm.java
  module-common/src/main/java/kernel/jdon/modulecommon/log/MdcPreference.java
  module-common/src/main/java/kernel/jdon/modulecommon/log/aspect/QueryCounterAspect.java
  module-common/src/main/java/kernel/jdon/modulecommon/log/config/P6SpyConfig.java
  module-common/src/main/java/kernel/jdon/modulecommon/log/filter/MdcLoggingFilter.java
  module-common/src/main/java/kernel/jdon/modulecommon/log/interceptor/ConnectionProxyHandler.java
  module-common/src/main/java/kernel/jdon/modulecommon/log/interceptor/PreparedStatementProxyHandler.java
  module-common/src/main/java/kernel/jdon/modulecommon/util/DateParserUtil.java
  module-common/src/main/java/kernel/jdon/modulecommon/util/StringUtil.java
  module-crawler/src/main/java/kernel/jdon/crawler/global/error/code/InflearnErrorCode.java
  module-crawler/src/main/java/kernel/jdon/crawler/global/error/code/SkillErrorCode.java
  module-crawler/src/main/java/kernel/jdon/crawler/global/error/code/WantedErrorCode.java
  module-crawler/src/main/java/kernel/jdon/crawler/global/error/exception/CrawlerException.java
  module-crawler/src/main/java/kernel/jdon/crawler/global/error/exception/GlobalExceptionHandler.java
  module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/InflearnCrawlerService.java
  module-crawler/src/main/java/kernel/jdon/crawler/wanted/service/WantedCrawlerService.java
Labels: ✏️ Fix

#301 Feature: 유저의 로그인 상태를 확인할 수 있는 API 구현
  module-api/src/main/java/kernel/jdon/auth/controller/AuthController.java
  module-api/src/main/java/kernel/jdon/auth/service/JdonOAuth2UserService.java
  module-api/src/main/java/kernel/jdon/config/auth/JdonAuthExceptionHandler.java
  module-api/src/main/java/kernel/jdon/config/auth/OAuth2SecurityConfig.java
  module-api/src/main/java/kernel/jdon/global/exception/AuthException.java
  module-api/src/main/java/kernel/jdon/global/exception/GlobalExceptionHandler.java
Labels: 🐞🔨 Bugfix, :sparkles: Feature

#303 Fix: Modify api response of check LoginStatus
  module-api/src/main/java/kernel/jdon/auth/controller/AuthController.java
  module-api/src/main/java/kernel/jdon/auth/dto/AuthExceptionResponse.java
  module-api/src/main/java/kernel/jdon/auth/dto/response/GetLoginStatusResponse.java
  module-api/src/main/java/kernel/jdon/config/auth/OAuth2SecurityConfig.java
Labels: ✏️ Fix

#304 Refactor: 커피챗 상세조회 API를 DDD기반 레이어드 아키텍처로 변경
  module-api/src/main/java/kernel/jdon/coffeechat/controller/CoffeeChatController.java
  module-api/src/main/java/kernel/jdon/coffeechat/repository/CoffeeChatRepository.java
  module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatApplyFacade.java
  module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatService.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/application/CoffeeChatFacade.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatInfoMapper.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatService.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatStore.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/error/CoffeeChatErrorCode.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatRepository.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatStoreImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatDto.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatDtoMapper.java
  module-api/src/test/java/kernel/jdon/moduleapi/coffeechat/controller/CoffeeChatControllerTest.java
  module-api/src/test/java/kernel/jdon/moduleapi/coffeechat/service/CoffeeChatServiceTest.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/coffeechat/application/CoffeeChatFacadeTest.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatServiceImplTest.java
Labels: 🔨 Refactor

#310 Refactor: Faq 패키지 구조 변경
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/core/FaqReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/core/FaqServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/core/FaqStore.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/infrastructure/FaqReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/infrastructure/FaqStoreImpl.java
Labels: 🐞🔨 Bugfix, 🔨 Refactor

#313 Refactor: 직군 별 직무 조회 API 추상화 리팩토링
  module-api/src/main/java/kernel/jdon/jobcategory/controller/JobCategoryController.java
  module-api/src/main/java/kernel/jdon/jobcategory/dto/response/FindListJobGroupResponse.java
  module-api/src/main/java/kernel/jdon/jobcategory/error/JobCategoryErrorCode.java
  module-api/src/main/java/kernel/jdon/jobcategory/repository/JobCategoryRepository.java
  module-api/src/main/java/kernel/jdon/jobcategory/service/JobCategoryService.java
  module-api/src/main/java/kernel/jdon/member/service/MemberService.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jobcategory/application/JobCategoryFacade.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jobcategory/core/JobCategoryInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jobcategory/core/JobCategoryReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jobcategory/core/JobCategoryService.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jobcategory/core/JobCategoryServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jobcategory/infrastructure/JobCategoryReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jobcategory/infrastructure/JobCategoryRepository.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jobcategory/presentation/JobCategoryController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jobcategory/presentation/JobCategoryDto.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jobcategory/presentation/JobCategoryMapper.java
Labels: 🔨 Refactor

#317 Refactor: 커피챗 목록 조회 API 추상화 리팩토링
  module-api/src/main/java/kernel/jdon/coffeechat/controller/CoffeeChatController.java
  module-api/src/main/java/kernel/jdon/coffeechat/dto/request/CreateCoffeeChatRequest.java
  module-api/src/main/java/kernel/jdon/coffeechat/dto/request/UpdateCoffeeChatRequest.java
  module-api/src/main/java/kernel/jdon/coffeechat/dto/response/ApplyCoffeeChatResponse.java
  module-api/src/main/java/kernel/jdon/coffeechat/dto/response/CreateCoffeeChatResponse.java
  module-api/src/main/java/kernel/jdon/coffeechat/dto/response/DeleteCoffeeChatResponse.java
  module-api/src/main/java/kernel/jdon/coffeechat/dto/response/FindCoffeeChatListResponse.java
  module-api/src/main/java/kernel/jdon/coffeechat/dto/response/FindCoffeeChatResponse.java
  module-api/src/main/java/kernel/jdon/coffeechat/dto/response/UpdateCoffeeChatResponse.java
  module-api/src/main/java/kernel/jdon/coffeechat/repository/CoffeeChatRepository.java
  module-api/src/main/java/kernel/jdon/coffeechat/repository/CustomCoffeeChatRepository.java
  module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatApplyFacade.java
  module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatService.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/application/CoffeeChatFacade.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatCommand.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatService.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatSortCondition.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatReaderInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatReaderMapper.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatRepository.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatRepositoryImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CustomCoffeeChatRepository.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatCondition.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatDto.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatDtoMapper.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/WebConfig.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/page/CustomPageInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/page/PageInfoRequest.java
Labels: 🔨 Refactor

#324 Fix: 커피챗 목록 조회 API host 직군 항목 필드명 변경
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatReaderInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatDto.java
Labels: ✏️ Fix

#329 Feature: Review 엔티티 생성
  module-domain/src/main/java/kernel/jdon/moduledomain/review/domain/Review.java
  module-domain/src/main/java/kernel/jdon/moduledomain/review/repository/ReviewDomainRepository.java
Labels: :sparkles: Feature

#326 Fix: referer이 null 인 상황을 고려하여 redirect하도록 수정
  module-api/src/main/java/kernel/jdon/auth/util/AesUtil.java
  module-api/src/main/java/kernel/jdon/auth/util/HmacUtil.java
  module-api/src/main/java/kernel/jdon/auth/util/RedirectUrlUtil.java
  module-api/src/main/java/kernel/jdon/auth/util/SecretKeyConstants.java
  module-api/src/main/java/kernel/jdon/member/service/MemberService.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/AllowOriginProperties.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/JdonAuthExceptionHandler.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/JdonLogoutSuccessHandler.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/JdonOAuth2AuthenticationSuccessHandler.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/LoginRedirectUrlProperties.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/LogoutRedirectUrlProperties.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/OAuth2SecurityConfig.java
  module-api/src/main/resources/application-dev.yml
  module-api/src/main/resources/application-local.yml
  module-api/src/main/resources/application-prod.yml
Labels: 🐞🔨 Bugfix

#333 Test: 직군 목록 조회 API 단위 테스트 작성
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jobcategory/core/JobCategoryInfo.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/jobcategory/application/JobCategoryFacadeTest.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/jobcategory/core/JobCategoryServiceImplTest.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/skill/application/SkillFacadeTest.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/skill/core/SkillServiceImplTest.java
  module-api/src/test/java/kernel/jdon/util/JsonFileReader.java
  module-api/src/test/resources/giventest/jobcategory/facade/1_jobGroupList_1.json
  module-api/src/test/resources/giventest/jobcategory/serviceimpl/1_jobcategory_1.json
  module-api/src/test/resources/giventest/jobcategory/serviceimpl/1_jobcategory_2.json
  module-api/src/test/resources/giventest/skill/facade/4_dataListBySkill_1.json
  module-api/src/test/resources/giventest/skill/serviceimpl/3_jobCategorySkillList.json
Labels: :test_tube: Test

#334 Refactor: 찜하기/취소하기, 찜 조회하기 API 페이징 변경
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/application/FavoriteFacade.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/core/FavoriteInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/core/FavoriteInfoMapper.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/core/FavoriteReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/core/FavoriteService.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/core/FavoriteServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/infrastructure/FavoriteReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/infrastructure/FavoriteReaderInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/infrastructure/FavoriteStoreImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/presentation/FavoriteController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/presentation/FavoriteDto.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/presentation/FavoriteDtoMapper.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/favorite/application/FavoriteFacadeTest.java
Labels: 🔨 Refactor

#327 Feature: JD 상세조회 API 구현
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/application/JdFacade.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdInfoMapper.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdService.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/error/JdErrorCode.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/JdReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/WantedJdRepository.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdDto.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdMapper.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/OAuth2SecurityConfig.java
  module-api/src/main/java/kernel/jdon/wantedjd/.gitkeep
  module-api/src/main/java/kernel/jdon/wantedjd/repository/WantedJdRepository.java
  module-api/src/main/resources/application-dev.yml
  module-api/src/main/resources/application-local.yml
  module-api/src/main/resources/application-prod.yml
  module-domain/src/main/java/kernel/jdon/wantedjd/domain/WantedJd.java
  module-domain/src/main/java/kernel/jdon/wantedjdskill/domain/WantedJdSkill.java
Labels: :sparkles: Feature, ✏️ Fix

#342 Feature: JD 목록 조회 API 구현
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/core/FavoriteInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/infrastructure/FavoriteReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/application/JdFacade.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdService.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/CustomWantedJdRepository.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/JdReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/JdReaderImplMapper.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/JdReaderInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/WantedJdRepository.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/WantedJdRepositoryImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdDto.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdDtoMapper.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jobcategory/core/JobCategoryReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/SkillReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/SkillService.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/inflearnjd/InflearnJdSkillReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/CustomSkillRepository.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillRepository.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillRepositoryCustom.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillRepositoryImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/page/CustomJpaPageInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/page/CustomPageInfo.java
Labels: :sparkles: Feature, 🔨 Refactor

#347 Feature: 리뷰 목록조회, 생성 API 구현
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/JdReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/JdReaderInfoMapper.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/application/ReviewFacade.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewCommand.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewService.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewStore.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/error/ReviewErrorCode.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/infrastructure/CustomReviewRepository.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/infrastructure/ReviewReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/infrastructure/ReviewReaderInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/infrastructure/ReviewReaderInfoMapper.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/infrastructure/ReviewRepository.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/infrastructure/ReviewRepositoryImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/infrastructure/ReviewStoreImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/presentation/ReviewController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/presentation/ReviewDto.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/presentation/ReviewDtoMapper.java
  module-domain/src/main/java/kernel/jdon/moduledomain/review/domain/Review.java
Labels: :sparkles: Feature

#337 Refactor: 멤버 정보 조회 & 수정 API를 레이어드 아키텍처로 refactor
  module-api/src/main/java/kernel/jdon/auth/controller/AuthController.java
  module-api/src/main/java/kernel/jdon/member/controller/MemberController.java
  module-api/src/main/java/kernel/jdon/member/dto/request/UpdateMemberRequest.java
  module-api/src/main/java/kernel/jdon/member/dto/response/FindMemberResponse.java
  module-api/src/main/java/kernel/jdon/member/dto/response/UpdateMemberResponse.java
  module-api/src/main/java/kernel/jdon/member/service/MemberService.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/application/MemberFacade.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/core/MemberCommand.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/core/MemberFactory.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/core/MemberInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/core/MemberInfoMapper.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/core/MemberReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/core/MemberService.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/core/MemberServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/core/MemberStore.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/infrastructure/MemberFactoryImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/infrastructure/MemberReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/infrastructure/MemberStoreImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/presentation/MemberController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/presentation/MemberDto.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/presentation/MemberDtoMapper.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/SkillReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/annotation/validate/Gender.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/annotation/validate/isPastDate.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/validate/GenderValidator.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/validate/PastDateValidator.java
  module-domain/src/main/java/kernel/jdon/member/domain/Gender.java
  module-domain/src/main/java/kernel/jdon/member/domain/Member.java
Labels: 🔨 Refactor

#345 Refactor: 닉네임 중복 확인 API를 레이어드 아키텍처에 맞게 refactor
  module-api/src/main/java/kernel/jdon/member/controller/MemberController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/application/MemberFacade.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/core/MemberCommand.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/core/MemberReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/core/MemberService.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/core/MemberServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/infrastructure/MemberReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/infrastructure/MemberStoreImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/presentation/MemberController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/presentation/MemberDto.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/presentation/MemberDtoMapper.java
Labels: 🔨 Refactor

#351 Feature: 리뷰 삭제 API 구현
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/application/ReviewFacade.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewCommand.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewService.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewStore.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/error/ReviewErrorCode.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/infrastructure/ReviewReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/infrastructure/ReviewStoreImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/presentation/ReviewController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/presentation/ReviewDtoMapper.java
Labels: :sparkles: Feature

#357 Feature: 커피챗 상세 조회시 응답에 로그인 유저의 기존 신청여부 추가
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/application/CoffeeChatFacade.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatInfoMapper.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatService.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatDto.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/coffeechat/application/CoffeeChatFacadeTest.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatServiceImplTest.java
  module-domain/src/main/java/kernel/jdon/coffeechat/domain/CoffeeChat.java
Labels: :sparkles: Feature, :test_tube: Test

#356 Fix: JD 상세조회 응답 항목 reviewCount 추가, 기술 스택 목록 중복 제거
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdInfoMapper.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/JdReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdDto.java
  module-domain/src/main/java/kernel/jdon/wantedjd/domain/WantedJd.java
Labels: 🐞🔨 Bugfix, ✏️ Fix

#336 Fix: 검색할 때 영어뿐만 아니라, 한글 또는 연관된 단어로 검색할 수 있도록 수정
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/core/FavoriteServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillKeywordManager.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillRepositoryImpl.java
  module-domain/src/main/java/kernel/jdon/skill/domain/BackendSkillType.java
  module-domain/src/main/java/kernel/jdon/skill/domain/FrontendSkillType.java
  module-domain/src/main/java/kernel/jdon/skill/domain/SkillType.java
Labels: 🐞🔨 Bugfix

#358 Refactor: 회원가입, 로그인 상태 확인 API 레이어드 아키텍처에 맞게 refactor
  module-api/src/main/java/kernel/jdon/auth/controller/AuthController.java
  module-api/src/main/java/kernel/jdon/auth/service/AuthService.java
  module-api/src/main/java/kernel/jdon/auth/service/JdonOAuth2UserService.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/auth/error/AuthErrorCode.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/auth/util/CryptoManager.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/application/MemberFacade.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/core/MemberCommand.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/core/MemberFactory.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/core/MemberInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/core/MemberService.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/core/MemberServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/core/MemberStore.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/infrastructure/MemberFactoryImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/infrastructure/MemberStoreImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/presentation/MemberController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/presentation/MemberDto.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/presentation/MemberDtoMapper.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/annotation/validate/IsPastDate.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/JdonAuthExceptionHandler.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/util/SessionUserUtil.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/validate/PastDateValidator.java
  module-domain/src/main/java/kernel/jdon/member/domain/Member.java
Labels: 🔨 Refactor

#361 Refactor: 탈퇴하는 API & OAuth2 서비스 로직 레이어드 아키텍처기반으로 refactor
  module-api/src/main/java/kernel/jdon/auth/controller/AuthController.java
  module-api/src/main/java/kernel/jdon/auth/dto/SessionUserInfo.java
  module-api/src/main/java/kernel/jdon/auth/dto/UserInfoFromOAuth2.java
  module-api/src/main/java/kernel/jdon/auth/dto/response/GetLoginStatusResponse.java
  module-api/src/main/java/kernel/jdon/auth/service/JdonOAuth2UserService.java
  module-api/src/main/java/kernel/jdon/auth/util/AesUtil.java
  module-api/src/main/java/kernel/jdon/auth/util/HmacUtil.java
  module-api/src/main/java/kernel/jdon/member/service/MemberService.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/auth/core/CustomOAuth2UserService.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/auth/core/CustomOAuth2UserServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/auth/core/JdonOAuth2User.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/auth/core/OAuth2ProviderComposite.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/auth/core/OAuth2Strategy.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/auth/error/AuthErrorCode.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/auth/infrastructure/GithubOAuth2StrategyImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/auth/infrastructure/KakaoOAuth2StrategyImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/auth/util/CryptoManager.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/auth/util/SecretKeyConstants.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/presentation/FavoriteController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/application/MemberFacade.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/core/MemberCommand.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/core/MemberInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/core/MemberReader.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/core/MemberService.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/core/MemberServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/core/MemberStore.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/infrastructure/MemberReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/infrastructure/MemberStoreImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/presentation/MemberController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/presentation/MemberDto.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/member/presentation/MemberDtoMapper.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/presentation/ReviewController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/presentation/SkillController.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/JdonAuthExceptionHandler.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/JdonLogoutSuccessHandler.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/JdonOAuth2AuthenticationSuccessHandler.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/OAuth2SecurityConfig.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/RedirectUrlUtil.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/web/LoginUserArgumentResolver.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/config/web/WebConfig.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/dto/SessionUserInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/global/util/SessionUserUtil.java
Labels: 🔨 Refactor

#365 BugFix: 커피챗 상세조회시 필드명 prefix 제외되는 이슈 수정
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatDto.java
Labels: 🐞🔨 Bugfix

#364 Refactor: DTO에 final 키워드 추가
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/JdReaderInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdDto.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jobcategory/core/JobCategoryInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jobcategory/presentation/JobCategoryDto.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/SkillCommand.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/SkillInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillReaderInfoMapper.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/inflearnjd/InflearnJdSkillReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/wantedjd/WantedJdSkillReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/presentation/SkillDto.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/jobcategory/application/JobCategoryFacadeTest.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/skill/application/SkillFacadeTest.java
  module-api/src/test/resources/giventest/jobcategory/facade/1_jobGroupList_1.json
  module-api/src/test/resources/giventest/skill/facade/4_dataListBySkill_1.json
Labels: 🔨 Refactor, :test_tube: Test

#354 Refactor: 찜하기/취소하기, 찜 조회하기 컨벤션에 맞게 수정
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/application/FavoriteFacade.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/core/FavoriteFactory.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/core/FavoriteService.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/core/FavoriteServiceImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/infrastructure/FavoriteFactoryImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/infrastructure/FavoriteReaderImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/infrastructure/FavoriteStoreImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/presentation/FavoriteController.java
  module-api/src/test/java/kernel/jdon/moduleapi/domain/favorite/application/FavoriteFacadeTest.java
Labels: ✏️ Fix

#377 Refactor: 커피챗 도메인 DTO에 final 키워드 추가 및 커피챗 목록 조회 API 응답 viewCount 추가
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatCommand.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatReaderInfo.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatRepositoryImpl.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatDto.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdController.java
  module-api/src/main/java/kernel/jdon/moduleapi/domain/review/presentation/ReviewController.java
Labels: :sparkles: Feature, 🔨 Refactor
